# shellcheck shell=bash
# =============================================================================
# 09-config.sh — device identity, default config.yaml, secret perms, pairing.
#
# Pure file-write helpers. None of these touch systemd, apt, or hardware.
# Idempotent: generate_device_id never overwrites an existing UUID and
# generate_default_config skips when config.yaml is already on disk.
# =============================================================================

# ─── Generate Device Identity ────────────────────────────────────────────────

generate_device_id() {
    # Create a stable device UUID. Once generated, never overwrite.
    if [ -f "${DEVICE_ID_FILE}" ]; then
        info "Device identity exists: $(cat "${DEVICE_ID_FILE}")"
        return
    fi

    local device_id
    if [ -f /proc/sys/kernel/random/uuid ]; then
        device_id=$(cat /proc/sys/kernel/random/uuid)
    elif command -v python3 >/dev/null 2>&1; then
        device_id=$(python3 -c "import uuid; print(uuid.uuid4())")
    elif command -v openssl >/dev/null 2>&1; then
        device_id=$(openssl rand -hex 16)
    else
        device_id="$(hostname)-$(date +%s)-$$"
    fi

    echo "$device_id" > "${DEVICE_ID_FILE}"
    chmod 644 "${DEVICE_ID_FILE}"
    info "Device identity generated: ${device_id}"
}

# ─── Generate Default Config ────────────────────────────────────────────────

generate_default_config() {
    local config_file="${CONFIG_DIR}/config.yaml"

    # Idempotent: skip if config already exists
    if [ -f "$config_file" ]; then
        info "Config already exists at ${config_file}, skipping generation."
        return
    fi

    info "Generating default config at ${config_file}..."

    # Read device ID (first 8 chars for agent name)
    local device_id=""
    if [ -f "${DEVICE_ID_FILE}" ]; then
        device_id=$(cat "${DEVICE_ID_FILE}")
    fi
    local short_id="${device_id:0:8}"

    # Use custom name if provided via --name flag
    local agent_name="${DRONE_NAME:-ados-${short_id}}"

    # Auto-detect FC serial port
    local fc_port=""
    for pattern in /dev/ttyACM* /dev/ttyAMA* /dev/ttyUSB*; do
        for port in $pattern; do
            if [ -e "$port" ]; then
                fc_port="$port"
                break 2
            fi
        done
    done

    if [ -n "$fc_port" ]; then
        info "Detected flight controller at: ${fc_port}"
    fi

    # Resolved agent profile, normalised to the underscore form the
    # AgentConfig validator accepts (drone | ground_station | auto).
    # install.sh exports ADOS_PROFILE before dispatching here; if it is
    # somehow unset (manual reentry) fall back to "auto" so the agent
    # still resolves at runtime via /etc/ados/profile.conf.
    local agent_profile="${ADOS_PROFILE:-auto}"
    if [ "$agent_profile" = "ground-station" ]; then
        agent_profile="ground_station"
    fi

    cat > "$config_file" <<CFGEOF
# ADOS Drone Agent Configuration
# Generated by install.sh on $(date -Iseconds 2>/dev/null || date)
# Docs: https://docs.altnautica.com/drone-agent/config

agent:
  device_id: "${short_id}"
  name: "${agent_name}"
  profile: "${agent_profile}"
  tier: "auto"

mavlink:
  serial_port: "${fc_port}"
  baud_rate: 57600
  system_id: 1
  component_id: 191

logging:
  level: "info"
  max_size_mb: 50
  keep_count: 5
  flight_log_dir: "/var/ados/logs/flights"

server:
  mode: "local"
  telemetry_rate: 2
  heartbeat_interval: 5
  mqtt_transport: "websockets"
  mqtt_username: "ados"
  mqtt_password: ""

security:
  api:
    cors_enabled: true

scripting:
  rest_api:
    enabled: true
    host: "0.0.0.0"
    port: 8080

pairing:
  convex_url: "${CONVEX_URL}"
  beacon_interval: 30
  heartbeat_interval: 60

discovery:
  mdns_enabled: true

# Video pipeline defaults. Empty cloud_relay_url means local mediamtx
# only; configure post-install when a cloud relay is ready.
video:
  mode: "auto"
  cloud_relay_url: ""
  record: false
  camera:
    width: 1280
    height: 720
    fps: 30
    codec: "h264"
    bitrate_kbps: 4000
CFGEOF

    chmod 0600 "$config_file"
    info "Default config written."
}

# ─── Harden Secret File Permissions ─────────────────────────────────────────

harden_secret_perms() {
    # Idempotent: only chmod files that exist; absence is fine on first install.
    # Tightens secrets in /etc/ados to 0600 (root-only). All ados-* services run as root.
    for f in "${CONFIG_DIR}/pairing.json" \
             "${CONFIG_DIR}/config.yaml" \
             "${CONFIG_DIR}/setup-token" \
             "${CONFIG_DIR}/env"; do
        if [ -f "$f" ]; then chmod 0600 "$f" 2>/dev/null || true; fi
    done
    if [ -d "${CONFIG_DIR}/plugin-keys" ]; then
        chmod 0700 "${CONFIG_DIR}/plugin-keys" 2>/dev/null || true
        find "${CONFIG_DIR}/plugin-keys" -maxdepth 1 -type f -name '*.pem' \
            -exec chmod 0600 {} + 2>/dev/null || true
    fi
    if [ -d "${CONFIG_DIR}/wfb" ]; then
        find "${CONFIG_DIR}/wfb" -maxdepth 1 -type f -name '*.key' \
            -exec chmod 0600 {} + 2>/dev/null || true
    fi
}

# ─── Provision First-Party Plugin Trust Keys ────────────────────────────────

provision_plugin_keys() {
    # Drop the first-party publisher public keys at /etc/ados/plugin-keys/
    # so the agent can verify signed .adosplug archives against the
    # FIRST_PARTY_SIGNERS allowlist. Keys ship inside the package at
    # scripts/plugin-keys/ and get persisted by 11-artifacts.sh to
    # /opt/ados/source/scripts/plugin-keys/ for the curl-pipe path.
    # Idempotent: overwrites are fine since the key bytes are stable
    # across reinstalls.
    local dst_dir="${CONFIG_DIR}/plugin-keys"
    install -d -m 0700 "${dst_dir}"

    local copied=0
    for src_dir in \
        "${PKG_DIR:-/opt/ados}/scripts/plugin-keys" \
        "/opt/ados/source/scripts/plugin-keys" \
    ; do
        [ -d "${src_dir}" ] || continue
        for pem in "${src_dir}"/*.pem; do
            [ -f "${pem}" ] || continue
            install -m 0600 "${pem}" "${dst_dir}/$(basename "${pem}")"
            copied=1
        done
        if [ "${copied}" -eq 1 ]; then
            return 0
        fi
    done
}

# ─── Seed Default Peripheral Manifests ──────────────────────────────────────

seed_default_peripherals() {
    # Drop the BOM peripheral manifests at /etc/ados/peripherals/ so the
    # webapp Peripherals page renders the FC, GPS, RTL8812EU adapter,
    # OLED, SPI LCD, and USB camera entries on a fresh board even
    # before any plugin lights them up. Idempotent: skips files that
    # are already present so operator-edited manifests survive
    # reinstalls.
    local dst_dir="${CONFIG_DIR}/peripherals"
    install -d -m 0755 "${dst_dir}"

    local copied=0
    for src_dir in \
        "${PKG_DIR:-/opt/ados}/scripts/peripherals-seed" \
        "/opt/ados/source/scripts/peripherals-seed" \
    ; do
        [ -d "${src_dir}" ] || continue
        for manifest in "${src_dir}"/*.yaml; do
            [ -f "${manifest}" ] || continue
            local target="${dst_dir}/$(basename "${manifest}")"
            if [ ! -f "${target}" ]; then
                install -m 0644 "${manifest}" "${target}"
                copied=$((copied + 1))
            fi
        done
        if [ "${copied}" -gt 0 ]; then
            info "Seeded ${copied} default peripheral manifest(s)"
            return 0
        fi
    done
}

# ─── Write Pairing State ────────────────────────────────────────────────────

write_pairing() {
    local code="$1"
    local pairing_file="${CONFIG_DIR}/pairing.json"
    local code_upper
    code_upper=$(echo "$code" | tr '[:lower:]' '[:upper:]')

    info "Setting pairing code: ${code_upper}"
    cat > "$pairing_file" <<PAIREOF
{
  "pairing_code": "${code_upper}",
  "code_created_at": $(date +%s)
}
PAIREOF
    chmod 0600 "$pairing_file"
}
