//! @generated by scripts/build-design-tokens.py — do not edit.
//!
//! Brand colour roles as 24-bit RGB for the LCD pages. Translucent roles are
//! omitted; the panels paint opaque colours only.

#![allow(dead_code)]

pub const BRAND_DARK_BG_CANVAS: (u8, u8, u8) = (10, 10, 15);
pub const BRAND_DARK_BG_SURFACE: (u8, u8, u8) = (12, 17, 32);
pub const BRAND_DARK_BG_RAISED: (u8, u8, u8) = (20, 28, 48);
pub const BRAND_DARK_BG_HOVER: (u8, u8, u8) = (18, 26, 46);
pub const BRAND_DARK_FG_PRIMARY: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_DARK_FG_SECONDARY: (u8, u8, u8) = (148, 163, 184);
pub const BRAND_DARK_FG_TERTIARY: (u8, u8, u8) = (125, 140, 163);
pub const BRAND_DARK_BORDER_DEFAULT: (u8, u8, u8) = (30, 41, 59);
pub const BRAND_DARK_BORDER_STRONG: (u8, u8, u8) = (51, 65, 85);
pub const BRAND_DARK_ACCENT_PRIMARY: (u8, u8, u8) = (58, 130, 255);
pub const BRAND_DARK_ACCENT_PRIMARY_HOVER: (u8, u8, u8) = (91, 154, 255);
pub const BRAND_DARK_ACCENT_SECONDARY: (u8, u8, u8) = (223, 241, 64);
pub const BRAND_DARK_ACCENT_FOREGROUND: (u8, u8, u8) = (10, 10, 15);
pub const BRAND_DARK_STATUS_SUCCESS: (u8, u8, u8) = (34, 197, 94);
pub const BRAND_DARK_STATUS_WARNING: (u8, u8, u8) = (245, 158, 11);
pub const BRAND_DARK_STATUS_SERIOUS: (u8, u8, u8) = (249, 115, 22);
pub const BRAND_DARK_STATUS_ERROR: (u8, u8, u8) = (239, 68, 68);
pub const BRAND_DARK_STATUS_INFO: (u8, u8, u8) = (91, 154, 255);
pub const BRAND_DARK_STATUS_ON: (u8, u8, u8) = (0, 0, 0);
pub const BRAND_DARK_FOCUS_RING: (u8, u8, u8) = (91, 154, 255);
pub const BRAND_DARK_MEDIA_LETTERBOX: (u8, u8, u8) = (0, 0, 0);
pub const BRAND_DARK_MEDIA_ON: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_DARK_HUD_PRIMARY: (u8, u8, u8) = (91, 154, 255);
pub const BRAND_DARK_HUD_DIM: (u8, u8, u8) = (75, 127, 181);
pub const BRAND_DARK_HUD_INK: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_DARK_HUD_INK_2: (u8, u8, u8) = (148, 163, 184);
pub const BRAND_DARK_HUD_MUTED: (u8, u8, u8) = (125, 140, 163);
pub const BRAND_DARK_HUD_GOOD: (u8, u8, u8) = (34, 197, 94);
pub const BRAND_DARK_HUD_WARN: (u8, u8, u8) = (245, 158, 11);
pub const BRAND_DARK_HUD_CRIT: (u8, u8, u8) = (239, 68, 68);
pub const BRAND_DARK_HUD_LOCK: (u8, u8, u8) = (34, 197, 94);
pub const BRAND_DARK_TERM_FG: (u8, u8, u8) = (0, 255, 65);

pub const BRAND_LIGHT_BG_CANVAS: (u8, u8, u8) = (255, 255, 255);
pub const BRAND_LIGHT_BG_SURFACE: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_LIGHT_BG_RAISED: (u8, u8, u8) = (255, 255, 255);
pub const BRAND_LIGHT_BG_HOVER: (u8, u8, u8) = (241, 245, 249);
pub const BRAND_LIGHT_FG_PRIMARY: (u8, u8, u8) = (15, 23, 42);
pub const BRAND_LIGHT_FG_SECONDARY: (u8, u8, u8) = (71, 85, 105);
pub const BRAND_LIGHT_FG_TERTIARY: (u8, u8, u8) = (100, 116, 139);
pub const BRAND_LIGHT_BORDER_DEFAULT: (u8, u8, u8) = (226, 232, 240);
pub const BRAND_LIGHT_BORDER_STRONG: (u8, u8, u8) = (203, 213, 225);
pub const BRAND_LIGHT_ACCENT_PRIMARY: (u8, u8, u8) = (37, 99, 235);
pub const BRAND_LIGHT_ACCENT_PRIMARY_HOVER: (u8, u8, u8) = (29, 78, 216);
pub const BRAND_LIGHT_ACCENT_SECONDARY: (u8, u8, u8) = (132, 204, 22);
pub const BRAND_LIGHT_ACCENT_FOREGROUND: (u8, u8, u8) = (255, 255, 255);
pub const BRAND_LIGHT_STATUS_SUCCESS: (u8, u8, u8) = (22, 163, 74);
pub const BRAND_LIGHT_STATUS_WARNING: (u8, u8, u8) = (217, 119, 6);
pub const BRAND_LIGHT_STATUS_SERIOUS: (u8, u8, u8) = (234, 88, 12);
pub const BRAND_LIGHT_STATUS_ERROR: (u8, u8, u8) = (220, 38, 38);
pub const BRAND_LIGHT_STATUS_INFO: (u8, u8, u8) = (37, 99, 235);
pub const BRAND_LIGHT_STATUS_ON: (u8, u8, u8) = (0, 0, 0);
pub const BRAND_LIGHT_FOCUS_RING: (u8, u8, u8) = (37, 99, 235);
pub const BRAND_LIGHT_MEDIA_LETTERBOX: (u8, u8, u8) = (0, 0, 0);
pub const BRAND_LIGHT_MEDIA_ON: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_LIGHT_HUD_PRIMARY: (u8, u8, u8) = (91, 154, 255);
pub const BRAND_LIGHT_HUD_DIM: (u8, u8, u8) = (75, 127, 181);
pub const BRAND_LIGHT_HUD_INK: (u8, u8, u8) = (248, 250, 252);
pub const BRAND_LIGHT_HUD_INK_2: (u8, u8, u8) = (148, 163, 184);
pub const BRAND_LIGHT_HUD_MUTED: (u8, u8, u8) = (125, 140, 163);
pub const BRAND_LIGHT_HUD_GOOD: (u8, u8, u8) = (22, 163, 74);
pub const BRAND_LIGHT_HUD_WARN: (u8, u8, u8) = (217, 119, 6);
pub const BRAND_LIGHT_HUD_CRIT: (u8, u8, u8) = (220, 38, 38);
pub const BRAND_LIGHT_HUD_LOCK: (u8, u8, u8) = (22, 163, 74);
pub const BRAND_LIGHT_TERM_FG: (u8, u8, u8) = (22, 163, 74);
