"""Pairing API routes."""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel

from ados.api.deps import get_agent_app
from ados.core.logging import get_logger
from ados.core.pairing import claim_with_external_code

router = APIRouter(tags=["pairing"])
log = get_logger("pairing_api")


class AcceptCodeRequest(BaseModel):
    code: str


class AcceptCodeResponse(BaseModel):
    ok: bool
    error: str | None = None
    message: str | None = None
    owner_id: str | None = None
    paired_at: float | None = None
    device_id: str | None = None


@router.post("/pairing/accept", response_model=AcceptCodeResponse)
async def accept_pairing_code(request: AcceptCodeRequest):
    """Accept a pairing code that was generated by Mission Control.

    Lets an operator pre-allocate a code on the Mission Control side and
    type it directly into this device's setup wizard, instead of typing
    the device code into Mission Control.
    """
    app = get_agent_app()
    result = await claim_with_external_code(app, request.code)
    if result.get("ok"):
        return AcceptCodeResponse(
            ok=True,
            owner_id=result.get("owner_id"),
            paired_at=result.get("paired_at"),
            device_id=result.get("device_id"),
        )
    return AcceptCodeResponse(
        ok=False,
        error=result.get("error"),
        message=result.get("message"),
    )

