"""The camera overlay provisioner's probation marker must carry what the boot
probe verifies.

``scripts/drivers/install-camera-overlay.sh`` writes a boot-critical device-tree
edit before the CSI sensor can enumerate, then arms
``/etc/ados/camera.probation`` so ``ados-camera-probe.service`` can confirm the
sensor on the next boot or restore the pre-overlay boot config. The probe can
only do that if the marker records WHAT to look for, so these tests pin the
marker's contract: the snapshot/boot-config pair it restores from, plus the
expected video node and sensor name it verifies against.

The script is driven entirely through its documented env overrides, so nothing
here touches a real ``/boot`` or needs root.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "drivers" / "install-camera-overlay.sh"
BOARDS_DIR = REPO_ROOT / "src" / "ados" / "hal" / "boards"

# A board whose YAML declares an overlay-required CSI camera with modes.
BOARD_ID = "cubie-a7z"

GOOD_EXTLINUX = (
    "## extlinux.conf generated by u-boot-update\n"
    "default l0\n"
    "menu title U-Boot menu\n"
    "prompt 0\n"
    "timeout 50\n"
    "\n"
    "label l0\n"
    "\tmenu label ADOS linux\n"
    "\tlinux /Image\n"
    "\tinitrd /uInitrd\n"
    "\tfdt /dtb\n"
    "\tappend root=UUID=0000 rootwait console=ttyS0,115200\n"
)


def _parse_conf(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, value = line.split("=", 1)
            out[key.strip()] = value.strip()
    return out


@pytest.fixture()
def rig(tmp_path: Path):
    """A temp boot tree shaped like the managed.list BSP image the provisioner
    supports, with a stub ``u-boot-update`` that regenerates extlinux.conf."""
    etc = tmp_path / "etc" / "ados"
    boot = tmp_path / "boot"
    dtbo = boot / "dtbo"
    extlinux_dir = boot / "extlinux"
    run = tmp_path / "run" / "ados"
    modules_dir = tmp_path / "etc" / "modules-load.d"
    for d in (etc, dtbo, extlinux_dir, run, modules_dir):
        d.mkdir(parents=True, exist_ok=True)

    # The BSP ships the overlay as a `.disabled` twin under a board-family
    # prefix; the provisioner globs for it by the YAML's overlay_ref token.
    (dtbo / "cubie-a7a-radxa-camera-13m-214.dtbo.disabled").write_bytes(b"\xd0\x0d\xfe\xed")
    (dtbo / "managed.list").write_text("cubie-a7a-base.dtbo\n")
    extlinux = extlinux_dir / "extlinux.conf"
    extlinux.write_text(GOOD_EXTLINUX)

    # Stub u-boot-update: rewrite extlinux.conf with the overlay line, the way
    # the real one regenerates it from managed.list.
    ubootbin = tmp_path / "u-boot-update"
    ubootbin.write_text(
        "#!/usr/bin/env bash\n"
        f'printf "%s" "{GOOD_EXTLINUX}" > "{extlinux}"\n'
        f'echo "\\tfdtoverlays /dtbo/cubie-a7a-radxa-camera-13m-214.dtbo" >> "{extlinux}"\n'
    )
    ubootbin.chmod(0o755)

    env = dict(os.environ)
    env.update(
        {
            "ADOS_OVERLAY_ALLOW_NONROOT": "1",
            "ADOS_ETC_DIR": str(etc),
            "ADOS_BOOT_DIR": str(boot),
            "ADOS_RUN_DIR": str(run),
            "ADOS_MODULES_LOAD_DIR": str(modules_dir),
            "ADOS_UBOOT_UPDATE_BIN": str(ubootbin),
            "ADOS_BOARDS_DIR": str(BOARDS_DIR),
            "ADOS_BOARD_ID": BOARD_ID,
        }
    )
    return {
        "env": env,
        "etc": etc,
        "boot": boot,
        "run": run,
        "extlinux": extlinux,
        "dtbo": dtbo,
    }


def _run(rig) -> subprocess.CompletedProcess:
    bash = shutil.which("bash")
    assert bash, "bash is required to drive the provisioner"
    return subprocess.run(
        [bash, str(SCRIPT)],
        env=rig["env"],
        capture_output=True,
        text=True,
    )


def test_probation_marker_carries_what_the_boot_probe_verifies(rig):
    result = _run(rig)
    assert result.returncode == 0, result.stderr

    marker = rig["etc"] / "camera.probation"
    assert marker.exists(), (
        "a newly enabled overlay must arm probation so the boot probe can "
        f"confirm or revert it\nstdout:\n{result.stdout}"
    )
    fields = _parse_conf(marker)

    # The revert pair: the probe restores `snapshot` over `boot_config`.
    assert fields["boot_config"] == str(rig["extlinux"])
    assert Path(fields["snapshot"]).is_file()
    assert Path(fields["snapshot"]).read_text() == GOOD_EXTLINUX, (
        "the snapshot must be the PRE-overlay boot config, byte for byte"
    )

    # The verification pair: without these the probe cannot tell a bound sensor
    # from an absent one, because the overlay is applied before the sensor can
    # enumerate.
    assert fields["expected_node"] == "/dev/video0"
    assert fields["sensor"] == "Sony IMX214"
    assert fields["camera_id"] == "csi-imx214"
    assert fields["overlay"] == "cubie-a7a-radxa-camera-13m-214"


def test_a_staged_overlay_signals_the_pending_reboot(rig):
    result = _run(rig)
    assert result.returncode == 0, result.stderr

    reboot_required = rig["run"] / "reboot-required"
    assert reboot_required.exists(), (
        "a staged overlay only takes effect after a reboot, so the install flow "
        "has to be told one is pending"
    )
    assert "camera-overlay" in reboot_required.read_text()

    conf = _parse_conf(rig["etc"] / "camera.conf")
    assert conf["overlay_state"] == "pending_reboot"
    # The keys the camera service needs to actually open the sensor, which the
    # probe's confirm path must preserve rather than rewrite away.
    assert conf["default_mode"] == "1920x1080@30"
    assert conf["vendor_isp"] == "true"


def test_a_second_run_is_idempotent_and_does_not_re_arm_probation(rig):
    # First run enables the overlay and arms probation.
    assert _run(rig).returncode == 0
    marker = rig["etc"] / "camera.probation"
    assert marker.exists()
    # Simulate the probe having consumed it on the next boot.
    marker.unlink()

    result = _run(rig)
    assert result.returncode == 0, result.stderr
    # Nothing newly enabled → no reboot pending → probation is NOT re-armed, so
    # a confirmed camera never gets re-probed (and never re-reverted).
    assert not marker.exists()
    conf = _parse_conf(rig["etc"] / "camera.conf")
    assert conf["overlay_state"] in {"enabled", "confirmed"}
