//! AIC8800 onboard-WiFi stability driver options at install time.
//!
//! The AIC8800 (AICSemi USB vendor `a69c`) is the onboard management Wi-Fi on
//! several SBCs (the Allwinner A733 Cubie A7S/A7Z, some Rock boards). Its
//! out-of-tree driver ships with aggressive default features that make the link
//! flap on a ~60s cadence — the driver locally generates its own disconnects
//! (`reason=2/3 locally_generated=1`) even on a strong signal, with heavy packet
//! loss. On-rig testing isolated the cause to the driver's DEFAULT feature set:
//!
//! - `ps_on=1` — the driver's OWN power-save, SEPARATE from the mac80211
//!   `iw ... power_save off` the agent already applies; a driver-level power-save
//!   sleeps the radio → beacon miss → periodic disconnect (the classic failure mode).
//! - `he_on=1` — WiFi-6/HE, whose negotiation fails on this platform (RX stuck at
//!   6 Mbit/s). A management link needs Wi-Fi-5 rates at most, so dropping HE costs
//!   nothing and removes the fault.
//! - `murx/mutx/mutx_on/ant_div=1` — MU-MIMO + antenna-diversity offloads.
//!
//! Disabling all of them took the link from ~33% packet loss + ~10 disconnects/
//! min to 0% loss / 0 disconnects (validated on the A7S).
//!
//! This step writes `/etc/modprobe.d/ados-aic8800.conf` with those options ONLY
//! when an AIC8800 is present. It takes effect on the next module load (next
//! boot). It deliberately does NOT reload the module at runtime: the AIC8800 IS
//! the operator's management interface, so `modprobe -r` mid-run would sever the
//! connection (unlike the RTL8812EU, which is never the management link, so its
//! sibling `rtl_modprobe` reconciler CAN hot-reload).
//!
//! Optional: a write failure degrades, never aborts the install. Runs after
//! `config_identity` so `/etc` is ready.

use std::path::Path;

use crate::ctx::Ctx;
use crate::graph::{Step, StepKind, StepOutcome};

/// The modprobe config path the step writes.
const MODPROBE_CONF_PATH: &str = "/etc/modprobe.d/ados-aic8800.conf";
/// The USB vendor ID of the AICSemi AIC8800 family (the detection gate).
const AIC_VENDOR_ID: &str = "a69c";

/// Render the full modprobe file body (bland header + option lines + newline).
///
/// Two `options` lines cover the two module-file names this driver ships under:
/// the Radxa A733 BSP builds `aic8800_fdrv_usb.ko` (so modprobe keys it
/// `aic8800_fdrv_usb`, NOT the internal name `aic8800_fdrv`), while some builds
/// name the file `aic8800_fdrv.ko`. An `options` line for a module that never
/// loads is a harmless no-op, so listing both is robust across BSPs.
fn render_file() -> String {
    let params = "ps_on=0 he_on=0 murx=0 mutx=0 mutx_on=0 ant_div=0";
    format!(
        "# ADOS Drone Agent — AIC8800 onboard-WiFi stability options.\n\
         # The out-of-tree driver's default features (its own power-save, WiFi-6/HE,\n\
         # MU-MIMO, antenna diversity) make the onboard management WiFi flap with\n\
         # self-generated disconnects even on a strong signal. Disabling them makes\n\
         # the link stable. Applies on the next module load. Generated by the agent;\n\
         # do not edit by hand.\n\
         options aic8800_fdrv_usb {params}\n\
         options aic8800_fdrv {params}\n"
    )
}

/// True when an AIC8800-family adapter (USB vendor `a69c`) is present on the box.
/// Best-effort sysfs scan; a read failure is treated as "not present".
fn aic8800_present() -> bool {
    let Ok(dir) = std::fs::read_dir("/sys/bus/usb/devices") else {
        return false;
    };
    for entry in dir.flatten() {
        if let Ok(vendor) = std::fs::read_to_string(entry.path().join("idVendor")) {
            if vendor.trim().eq_ignore_ascii_case(AIC_VENDOR_ID) {
                return true;
            }
        }
    }
    false
}

/// AIC8800 onboard-WiFi stability driver-options seed.
pub struct Aic8800Tune;

impl Step for Aic8800Tune {
    fn id(&self) -> &str {
        "aic8800_tune"
    }
    fn requires(&self) -> &[&str] {
        // After config so `/etc` exists; the AIC8800 driver is BSP-provided (not
        // built by our `dkms` step), so no driver-build dependency.
        &["config_identity"]
    }
    fn checkpoint(&self) -> Option<&str> {
        // No checkpoint: re-affirm the options file on every upgrade.
        None
    }
    fn kind(&self) -> StepKind {
        // Optional: a write problem must degrade, never abort the install.
        StepKind::Optional
    }
    fn run(&self, _ctx: &mut Ctx) -> StepOutcome {
        if !aic8800_present() {
            tracing::info!("no AIC8800 onboard WiFi present; skipping stability tune");
            return StepOutcome::Ok;
        }
        let body = render_file();
        let path = Path::new(MODPROBE_CONF_PATH);
        // Idempotent: skip the write when the file is already current.
        if std::fs::read_to_string(path)
            .map(|c| c == body)
            .unwrap_or(false)
        {
            tracing::info!("AIC8800 onboard-WiFi stability options already current");
            return StepOutcome::Ok;
        }
        if let Err(e) = write_file(path, &body) {
            tracing::warn!(error = %e, "failed to write AIC8800 stability options");
            return StepOutcome::Failed(format!("could not write {MODPROBE_CONF_PATH}: {e}"));
        }
        tracing::info!("wrote AIC8800 onboard-WiFi stability driver options (applies next boot)");
        StepOutcome::Ok
    }
}

/// Write `body` to `path` atomically (tmp + rename), creating the parent dir.
fn write_file(path: &Path, body: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("conf.tmp");
    std::fs::write(&tmp, body.as_bytes())?;
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_body_disables_the_unstable_features_for_both_module_names() {
        let body = render_file();
        assert!(body.starts_with("# ADOS Drone Agent"));
        // The A733 BSP module file name (proven on-rig to be the one that matches).
        assert!(body.contains("options aic8800_fdrv_usb ps_on=0 he_on=0"));
        // The alternate file name, for BSPs that build aic8800_fdrv.ko.
        assert!(body.contains("options aic8800_fdrv ps_on=0 he_on=0"));
        // Every unstable feature is disabled.
        for kv in [
            "ps_on=0",
            "he_on=0",
            "murx=0",
            "mutx=0",
            "mutx_on=0",
            "ant_div=0",
        ] {
            assert!(body.contains(kv), "missing {kv}");
        }
        assert!(body.ends_with('\n'));
    }

    #[test]
    fn body_never_enables_a_feature() {
        // A stray `=1` would re-enable a fault; the tune only ever disables.
        assert!(!render_file().contains("=1"));
    }
}
