//! Keep the node awake + quiet background package daemons at install time.
//!
//! An ADOS node is an always-on appliance on EVERY profile — a drone companion,
//! a ground station, a compute box, an operator workstation. Two default OS
//! behaviors sabotage that:
//!
//! 1. **Idle-suspend.** A desktop/systemd install idle-suspends (KDE/GNOME idle
//!    timer, a closed lid, a stray power/suspend key), which drops the node off
//!    the network mid-flight. The fix: mask every sleep target and write a logind
//!    drop-in that ignores the idle timer, the lid switch, and the power/suspend/
//!    hibernate keys. This runs on ALL profiles.
//!
//! 2. **Background package-update churn.** On a box with a full desktop the
//!    PackageKit daemon + GNOME Software / KDE Discover periodic auto-refresh pin
//!    the CPU at max clock (observed ~28% packagekitd + ~8% gnome-software on a
//!    Rock 5C ground station), which overheats a fanless SoC and adds jitter. The
//!    fix: mask PackageKit (the shared update backend that GNOME Software AND KDE
//!    Discover drive their periodic refresh through) and the fwupd metadata-refresh
//!    timer, and stop any running instance so the current boot goes quiet too.
//!    This runs ONLY when a desktop is present; on a headless node it is a clean
//!    no-op.
//!
//! Conservative + reversible: everything is a `systemctl mask` (a symlink to
//! `/dev/null`, undone with `unmask`) or a config drop-in — no package is purged.
//! Idempotent + fail-soft: a mask that is already applied, a unit that does not
//! exist, or a write problem degrades but never aborts the install. Runs after
//! `config_identity` so `/etc` is ready.

use std::path::Path;

use crate::ctx::Ctx;
use crate::exec;
use crate::graph::{Step, StepKind, StepOutcome};

/// The logind drop-in this step writes (keeps the appliance awake).
const LOGIND_NO_IDLE_CONF: &str = "/etc/systemd/logind.conf.d/90-ados-no-idle.conf";
/// A drop-in a prior installer wrote for the same purpose with a narrower
/// directive set. Superseded by `LOGIND_NO_IDLE_CONF`; removed on install so a
/// box never carries two overlapping no-sleep drop-ins.
const STALE_NOSLEEP_CONF: &str = "/etc/systemd/logind.conf.d/99-ados-nosleep.conf";

/// Every systemd sleep path an appliance must never take. Masking all five makes
/// the box unsuspendable regardless of which target something tries to activate.
/// Pure so it is unit-tested without systemd.
fn sleep_targets() -> [&'static str; 5] {
    [
        "sleep.target",
        "suspend.target",
        "hibernate.target",
        "hybrid-sleep.target",
        "suspend-then-hibernate.target",
    ]
}

/// The background package-update daemons/timers to mask WHEN a desktop is present.
/// PackageKit is the shared update backend that both GNOME Software and KDE
/// Discover drive their periodic auto-refresh through, so masking it starves both
/// of their background-refresh path; the fwupd timer is the daily firmware-metadata
/// refresh. Pure so it is unit-tested without systemd.
fn desktop_churn_units() -> [&'static str; 3] {
    [
        "packagekit.service",
        "packagekit-offline-update.service",
        "fwupd-refresh.timer",
    ]
}

/// Render the logind no-idle drop-in body (pure). Ignores the idle timer (both
/// the action and its zeroed timeout), the power/suspend/hibernate keys, and every
/// lid-switch variant (on external power, docked, and the base case) so nothing —
/// an idle console, a closed lid, a stray key — can put the appliance to sleep.
fn logind_no_idle_body() -> String {
    "# ADOS Drone Agent — keep the appliance awake.\n\
     # An ADOS node is an always-on appliance: never idle-suspend, and ignore the\n\
     # power/suspend/hibernate keys and the lid switch so a console keypress or a\n\
     # closed lid cannot put it to sleep. Generated by the agent; do not edit by hand.\n\
     [Login]\n\
     IdleAction=ignore\n\
     IdleActionSec=0\n\
     HandlePowerKey=ignore\n\
     HandleSuspendKey=ignore\n\
     HandleHibernateKey=ignore\n\
     HandleLidSwitch=ignore\n\
     HandleLidSwitchExternalPower=ignore\n\
     HandleLidSwitchDocked=ignore\n"
        .to_string()
}

/// The facts that decide whether a desktop is present. Kept as a plain struct so
/// the gate is a pure, unit-tested function separate from the system probe.
#[derive(Debug, Clone, Copy, Default)]
struct DesktopProbe {
    /// A display manager (gdm/sddm/lightdm, aliased to `display-manager.service`)
    /// is active.
    dm_active: bool,
    /// The GNOME shell binary is installed.
    gnome_shell: bool,
    /// The KDE Plasma shell binary is installed.
    plasmashell: bool,
}

/// True when the box has a desktop stack (a running display manager OR an
/// installed GNOME/KDE shell). "Installed" — not "showing" — is the right gate:
/// PackageKit + GNOME Software churn the moment a desktop stack is on disk, even
/// with no one logged in. Pure.
fn is_desktop(p: DesktopProbe) -> bool {
    p.dm_active || p.gnome_shell || p.plasmashell
}

/// Probe the live box for a desktop. Best-effort: any read failure reads as
/// "absent" so a headless node cleanly skips the desktop block.
fn probe_desktop() -> DesktopProbe {
    let dm_active = [
        "display-manager.service",
        "gdm.service",
        "gdm3.service",
        "sddm.service",
        "lightdm.service",
    ]
    .iter()
    .any(|u| exec::run_ok("systemctl", &["is-active", "--quiet", u]));
    DesktopProbe {
        dm_active,
        gnome_shell: binary_present("gnome-shell"),
        plasmashell: binary_present("plasmashell"),
    }
}

/// True when `name` resolves to an executable on PATH (a desktop shell binary
/// being installed is the broad desktop-present signal). Best-effort: probes the
/// shell's `command -v` (PATH-aware), falling back to the canonical bin dirs.
/// `name` is a fixed shell name here, so the `sh -c` interpolation is not a
/// user-input injection surface.
fn binary_present(name: &str) -> bool {
    exec::run_ok("sh", &["-c", &format!("command -v {name}")])
        || Path::new(&format!("/usr/bin/{name}")).exists()
        || Path::new(&format!("/bin/{name}")).exists()
}

/// True when `unit` has a unit file on this box (so we only mask what is really
/// there and report honestly). Best-effort: a spawn failure reads as absent.
fn unit_present(unit: &str) -> bool {
    let r = exec::run("systemctl", &["list-unit-files", "--no-legend", unit]);
    r.success() && r.stdout.contains(unit)
}

/// Write `body` to `path` atomically (tmp + rename), creating the parent dir, and
/// mark it world-readable (logind reads it as root; 0644 is the norm for a config
/// drop-in and is robust against a restrictive install-time umask).
fn write_conf(path: &Path, body: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("conf.tmp");
    std::fs::write(&tmp, body.as_bytes())?;
    std::fs::rename(&tmp, path)?;
    set_readable(path);
    Ok(())
}

#[cfg(unix)]
fn set_readable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o644));
}
#[cfg(not(unix))]
fn set_readable(_path: &Path) {}

/// Keep-awake + quiet-background-daemons provisioning.
pub struct Appliance;

impl Step for Appliance {
    fn id(&self) -> &str {
        "appliance"
    }
    fn requires(&self) -> &[&str] {
        // After config so `/etc` exists. Independent of the radio/systemd steps.
        &["config_identity"]
    }
    fn checkpoint(&self) -> Option<&str> {
        // No checkpoint: re-affirm the masks + drop-in on every upgrade.
        None
    }
    fn kind(&self) -> StepKind {
        // Optional: a mask/write problem must degrade, never abort the install.
        StepKind::Optional
    }
    fn run(&self, _ctx: &mut Ctx) -> StepOutcome {
        keep_awake();
        quiet_desktop_package_daemons();
        StepOutcome::Ok
    }
}

/// Mask every sleep target and install the logind no-idle drop-in (all profiles).
fn keep_awake() {
    // Mask every sleep path so nothing can suspend/hibernate the appliance. `mask`
    // is idempotent (already-masked → success no-op) and fail-soft here.
    let _ = exec::run(
        "systemctl",
        &[["mask"].as_slice(), sleep_targets().as_slice()].concat(),
    );

    // Drop the superseded narrower drop-in so only one no-sleep drop-in remains.
    if Path::new(STALE_NOSLEEP_CONF).exists() {
        let _ = std::fs::remove_file(STALE_NOSLEEP_CONF);
    }

    // Write the no-idle drop-in idempotently (skip when already current).
    let path = Path::new(LOGIND_NO_IDLE_CONF);
    let body = logind_no_idle_body();
    let already_current = std::fs::read_to_string(path)
        .map(|c| c == body)
        .unwrap_or(false);
    if already_current {
        tracing::info!("logind no-idle drop-in already current; sleep targets masked");
    } else if let Err(e) = write_conf(path, &body) {
        tracing::warn!(error = %e, "failed to write logind no-idle drop-in (applies next boot when written)");
    } else {
        tracing::info!("masked sleep targets + wrote logind no-idle drop-in");
    }

    // Best-effort SIGHUP so logind re-reads the drop-in this boot; NOT a restart
    // (a restart would drop live sessions). If it does not take, the drop-in
    // applies on the next boot.
    if !exec::run_ok("systemctl", &["reload", "systemd-logind"]) {
        tracing::info!("could not reload systemd-logind now; no-idle settings apply next boot");
    }
}

/// On a desktop box only, mask + stop the background package-update daemons that
/// pin the CPU. A clean no-op on a headless node.
fn quiet_desktop_package_daemons() {
    if !is_desktop(probe_desktop()) {
        tracing::info!("no desktop present; leaving package daemons untouched");
        return;
    }
    let mut masked = 0usize;
    for unit in desktop_churn_units() {
        if !unit_present(unit) {
            continue;
        }
        // Mask so it cannot be (re)activated, then stop the running instance so
        // the current boot goes quiet too. Both fail-soft.
        if exec::run_ok("systemctl", &["mask", unit]) {
            masked += 1;
        }
        let _ = exec::run("systemctl", &["stop", unit]);
    }
    tracing::info!(
        masked,
        "quieted background package-update daemons (desktop present)"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sleep_targets_cover_every_sleep_path() {
        let t = sleep_targets();
        for expected in [
            "sleep.target",
            "suspend.target",
            "hibernate.target",
            "hybrid-sleep.target",
            "suspend-then-hibernate.target",
        ] {
            assert!(t.contains(&expected), "missing sleep target {expected}");
        }
    }

    #[test]
    fn logind_body_ignores_idle_lid_and_keys() {
        let body = logind_no_idle_body();
        assert!(body.starts_with("# ADOS Drone Agent"));
        assert!(body.contains("[Login]"));
        for line in [
            "IdleAction=ignore",
            "IdleActionSec=0",
            "HandlePowerKey=ignore",
            "HandleSuspendKey=ignore",
            "HandleHibernateKey=ignore",
            "HandleLidSwitch=ignore",
            "HandleLidSwitchExternalPower=ignore",
            "HandleLidSwitchDocked=ignore",
        ] {
            assert!(body.contains(line), "missing logind directive {line}");
        }
        assert!(body.ends_with('\n'));
    }

    #[test]
    fn logind_body_never_re_enables_a_sleep_action() {
        // A stray `=suspend`/`=poweroff`/`=hibernate` would re-arm a sleep path;
        // every handled key/idle action must be `ignore` (the timeout is `0`).
        let body = logind_no_idle_body();
        for bad in ["=suspend", "=poweroff", "=hibernate", "=lock", "=halt"] {
            assert!(!body.contains(bad), "logind body must not set {bad}");
        }
    }

    #[test]
    fn desktop_gate_is_true_for_any_desktop_signal() {
        assert!(!is_desktop(DesktopProbe::default()));
        assert!(is_desktop(DesktopProbe {
            dm_active: true,
            ..Default::default()
        }));
        assert!(is_desktop(DesktopProbe {
            gnome_shell: true,
            ..Default::default()
        }));
        assert!(is_desktop(DesktopProbe {
            plasmashell: true,
            ..Default::default()
        }));
    }

    #[test]
    fn desktop_churn_units_are_the_background_updaters() {
        let u = desktop_churn_units();
        assert!(u.contains(&"packagekit.service"));
        assert!(u.contains(&"packagekit-offline-update.service"));
        assert!(u.contains(&"fwupd-refresh.timer"));
    }

    #[test]
    fn logind_conf_is_in_the_uninstall_removal_list() {
        // Install/uninstall symmetry: the drop-in this step writes must be in the
        // uninstall removal list so a purge leaves a clean box.
        let removed = crate::uninstall::dropin_files();
        assert!(
            removed.contains(&LOGIND_NO_IDLE_CONF),
            "{LOGIND_NO_IDLE_CONF} is written by install but not removed by uninstall"
        );
    }
}
