//! Config + identity: mint the device id, write `/etc/ados/profile.conf` +
//! `/etc/ados/config.yaml`, set the hostname (`--name`), persist the pairing
//! material (`--pair`), and delegate the display + camera overlay provisioning
//! to the battle-tested driver scripts. Required — the agent will not resolve
//! its profile or identity without it.
//!
//! Ports the pure file-write logic of `scripts/install.d/09-config.sh`
//! (`generate_device_id`, `generate_default_config`, `set_hostname`,
//! `write_pairing`) and delegates the two boot-config-editing overlay steps
//! (`install-display-overlay.sh` / `install-camera-overlay.sh`) via `exec` —
//! those carry brick-safe snapshot/restore logic that must not be re-ported.
//!
//! The slugify + the config-YAML builder are pure so a unit test exercises them
//! without touching the filesystem.

use std::path::Path;

use crate::ctx::Ctx;
use crate::env::{self, CONFIG_YAML, CONVEX_URL, DEVICE_ID_FILE, PAIRING_JSON, PROFILE_CONF};
use crate::exec;
use crate::graph::{Step, StepKind, StepOutcome};

/// Slugify a `--name` into a DNS-safe label: lowercase, `[a-z0-9-]` only,
/// runs of other chars collapse to a single `-`, leading/trailing `-`
/// trimmed, max 63 chars (then re-trim a trailing `-` the cut may expose).
/// Pure — mirrors the `sed` pipeline in `set_hostname`. Empty when nothing
/// usable survives.
pub fn slugify_hostname(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_dash = false;
    for ch in name.chars() {
        let c = ch.to_ascii_lowercase();
        if c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' {
            if c == '-' {
                if last_dash {
                    continue;
                }
                last_dash = true;
            } else {
                last_dash = false;
            }
            out.push(c);
        } else if !last_dash {
            // A run of disallowed chars collapses to a single '-'.
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_matches('-');
    let mut cut: String = trimmed.chars().take(63).collect();
    // The 63-char cut can leave a trailing '-'; trim it.
    while cut.ends_with('-') {
        cut.pop();
    }
    cut
}

/// Build the default `config.yaml` body (pure). Mirrors `generate_default_config`
/// in 09-config.sh: agent identity + the mavlink / logging / server / scripting /
/// pairing / discovery / video blocks. `short_id` is the first 8 hex of the
/// device id, `agent_name` is `--name` or `ados-<short_id>`, `fc_port` is the
/// auto-detected FC serial port (empty when none found).
pub fn default_config_yaml(
    short_id: &str,
    agent_name: &str,
    profile: &str,
    fc_port: &str,
) -> String {
    format!(
        "# ADOS Drone Agent Configuration\n\
# Generated by ados-installer\n\
# Docs: https://docs.altnautica.com/drone-agent/config\n\
\n\
agent:\n  \
device_id: \"{short_id}\"\n  \
name: \"{agent_name}\"\n  \
profile: \"{profile}\"\n  \
tier: \"auto\"\n\
\n\
mavlink:\n  \
serial_port: \"{fc_port}\"\n  \
baud_rate: 57600\n  \
system_id: 1\n  \
component_id: 191\n\
\n\
logging:\n  \
level: \"info\"\n  \
max_size_mb: 50\n  \
keep_count: 5\n  \
flight_log_dir: \"/var/ados/logs/flights\"\n\
\n\
server:\n  \
mode: \"local\"\n  \
telemetry_rate: 2\n  \
heartbeat_interval: 5\n  \
mqtt_transport: \"websockets\"\n  \
mqtt_username: \"ados\"\n  \
mqtt_password: \"\"\n\
\n\
security:\n  \
api:\n    \
cors_enabled: true\n\
\n\
scripting:\n  \
rest_api:\n    \
enabled: true\n    \
host: \"0.0.0.0\"\n    \
port: 8080\n\
\n\
pairing:\n  \
convex_url: \"{CONVEX_URL}\"\n  \
beacon_interval: 30\n  \
heartbeat_interval: 60\n\
\n\
discovery:\n  \
mdns_enabled: true\n\
\n\
# Video pipeline defaults. Empty cloud_relay_url means local mediamtx\n\
# only; configure post-install when a cloud relay is ready.\n\
video:\n  \
mode: \"auto\"\n  \
cloud_relay_url: \"\"\n  \
record: false\n  \
camera:\n    \
width: 1280\n    \
height: 720\n    \
fps: 30\n    \
codec: \"h264\"\n    \
bitrate_kbps: 4000\n"
    )
}

/// Build the `profile.conf` body (pure): the canonical YAML `profile: <p>` form.
pub fn profile_conf_body(profile: &str) -> String {
    format!("profile: {profile}\n")
}

/// Build the `pairing.json` body (pure). Mirrors `write_pairing`: the code is
/// uppercased and stamped with the creation epoch.
pub fn pairing_json(code: &str, created_at: u64) -> String {
    let upper = code.to_ascii_uppercase();
    format!("{{\n  \"pairing_code\": \"{upper}\",\n  \"code_created_at\": {created_at}\n}}\n")
}

/// Mint or read the stable 12-hex device id. Never overwrites an existing id
/// (the running agent's identity is derived from it). Prefers the kernel UUID
/// source, falling back to `getrandom` so the mint works on any host.
fn ensure_device_id() -> anyhow::Result<String> {
    let path = Path::new(DEVICE_ID_FILE);
    if let Ok(existing) = std::fs::read_to_string(path) {
        let trimmed = existing.trim();
        if !trimmed.is_empty() {
            tracing::info!(device_id = %trimmed, "device identity exists");
            return Ok(trimmed.to_string());
        }
    }
    let id = mint_device_id();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, format!("{id}\n"))?;
    set_mode(path, 0o644);
    tracing::info!(device_id = %id, "device identity generated");
    Ok(id)
}

/// Generate a fresh 12-hex device id. Reads `/proc/sys/kernel/random/uuid`
/// when present (matching the bash), else fills 6 bytes from `getrandom`.
fn mint_device_id() -> String {
    if let Ok(uuid) = std::fs::read_to_string("/proc/sys/kernel/random/uuid") {
        let hex: String = uuid
            .chars()
            .filter(|c| c.is_ascii_hexdigit())
            .take(12)
            .collect();
        if hex.len() == 12 {
            return hex.to_ascii_lowercase();
        }
    }
    let mut bytes = [0u8; 6];
    if getrandom::getrandom(&mut bytes).is_ok() {
        return hex::encode(bytes);
    }
    // Last-ditch deterministic-ish fallback (should never be reached): derive
    // from the process id + a fixed salt so we still produce 12 hex chars.
    let pid = std::process::id();
    format!("{pid:012x}").chars().take(12).collect()
}

/// Auto-detect the FC serial port. Mirrors the bash glob order
/// (`/dev/ttyACM* /dev/ttyAMA* /dev/ttyUSB*`), returning the first node found
/// or an empty string. The agent re-detects at runtime; this is only the seed.
fn detect_fc_port() -> String {
    for prefix in ["/dev/ttyACM", "/dev/ttyAMA", "/dev/ttyUSB"] {
        let dir = Path::new("/dev");
        if let Ok(read) = std::fs::read_dir(dir) {
            let base = prefix.trim_start_matches("/dev/");
            let mut matches: Vec<String> = read
                .flatten()
                .filter_map(|e| e.file_name().into_string().ok())
                .filter(|n| n.starts_with(base) && n.len() > base.len())
                .collect();
            matches.sort();
            if let Some(first) = matches.first() {
                return format!("/dev/{first}");
            }
        }
    }
    String::new()
}

/// Write the default config (skip-if-exists, matching `generate_default_config`).
/// A pre-existing config is left intact (an operator may have edited it / an
/// `--upgrade` preserves it); we only mint a fresh one on a clean box.
fn write_default_config(short_id: &str, name: Option<&str>, profile: &str) {
    let path = Path::new(CONFIG_YAML);
    if path.exists() {
        tracing::info!(
            path = CONFIG_YAML,
            "config already exists; leaving it intact"
        );
        return;
    }
    let agent_name = name
        .map(|n| n.to_string())
        .unwrap_or_else(|| format!("ados-{short_id}"));
    let fc_port = detect_fc_port();
    if !fc_port.is_empty() {
        tracing::info!(fc_port = %fc_port, "detected flight controller serial port");
    }
    let body = default_config_yaml(short_id, &agent_name, profile, &fc_port);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Err(e) = std::fs::write(path, body) {
        tracing::warn!(error = %e, "writing default config failed");
        return;
    }
    set_mode(path, 0o600);
    tracing::info!("default config written");
}

/// Persist the resolved profile to `/etc/ados/profile.conf` so it survives
/// reboots and a later `--upgrade`. Idempotent overwrite of the one-line file.
fn write_profile_conf(profile: &str) {
    let path = Path::new(PROFILE_CONF);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Err(e) = std::fs::write(path, profile_conf_body(profile)) {
        tracing::warn!(error = %e, "writing profile.conf failed");
    }
}

/// Set the system hostname from `--name` (slugified), rewrite the `/etc/hosts`
/// `127.0.1.1` line, and restart avahi so `<slug>.local` resolves. Best-effort
/// — a hostname failure must not abort the install.
fn set_hostname(name: &str) {
    let slug = slugify_hostname(name);
    if slug.is_empty() {
        tracing::warn!(
            name,
            "--name slugified to empty; leaving hostname unchanged"
        );
        return;
    }
    // hostnamectl is the canonical setter; fall back to /etc/hostname.
    if !exec::run_ok("hostnamectl", &["set-hostname", &slug]) {
        tracing::warn!(slug = %slug, "hostnamectl failed; writing /etc/hostname directly");
        let _ = std::fs::write("/etc/hostname", format!("{slug}\n"));
    } else {
        tracing::info!(slug = %slug, "hostname set");
    }
    rewrite_hosts_127_0_1_1(&slug);
    // Reconcile mDNS so <slug>.local resolves (best-effort).
    let _ = exec::run("systemctl", &["restart", "avahi-daemon"]);
}

/// Keep the `/etc/hosts` `127.0.1.1` line pointing at the new hostname so name
/// resolution does not stall. Rewrites that one line, or appends it.
fn rewrite_hosts_127_0_1_1(slug: &str) {
    let path = Path::new("/etc/hosts");
    let current = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return,
    };
    let new = rewrite_hosts_body(&current, slug);
    if new != current {
        let _ = std::fs::write(path, new);
    }
}

/// Rewrite (or append) the `127.0.1.1 <slug>` line in a `/etc/hosts` body
/// (pure). Replaces an existing `127.0.1.1 ...` line; otherwise appends one.
pub fn rewrite_hosts_body(hosts: &str, slug: &str) -> String {
    let had_trailing_newline = hosts.ends_with('\n');
    let mut found = false;
    let mut out: Vec<String> = Vec::new();
    for raw in hosts.lines() {
        let starts_127011 = raw
            .split_whitespace()
            .next()
            .map(|t| t == "127.0.1.1")
            .unwrap_or(false);
        if starts_127011 {
            out.push(format!("127.0.1.1\t{slug}"));
            found = true;
        } else {
            out.push(raw.to_string());
        }
    }
    if !found {
        out.push(format!("127.0.1.1\t{slug}"));
    }
    let mut joined = out.join("\n");
    if had_trailing_newline || !found {
        joined.push('\n');
    }
    joined
}

/// Persist the pairing material from `--pair CODE`.
fn write_pairing(code: &str) {
    let path = Path::new(PAIRING_JSON);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let body = pairing_json(code, now_epoch());
    if let Err(e) = std::fs::write(path, body) {
        tracing::warn!(error = %e, "writing pairing.json failed");
        return;
    }
    set_mode(path, 0o600);
    tracing::info!(code = %code.to_ascii_uppercase(), "pairing code written");
}

/// Delegate the display + camera overlay provisioning to the brick-safe driver
/// scripts under the resolved source dir. Best-effort: a missing script or a
/// non-zero exit only degrades (the bash treats both as non-fatal).
///
/// Display default is profile-aware (the bash inverts the two): a ground
/// station auto-detects its panel; a drone defaults to `none`. Camera is the
/// inverse — a drone defaults to `auto`, a ground station to `none` — but the
/// camera auto-enable is still operator-gated, so without an explicit
/// `--camera` we pass `none` to match the bash safety gate.
fn provision_overlays(ctx: &Ctx, source: Option<&Path>) {
    let source = match source {
        Some(s) => s,
        None => {
            tracing::warn!("no source dir resolved; skipping overlay provisioning");
            return;
        }
    };

    // ── Display ──
    let display_script = source.join("scripts/drivers/install-display-overlay.sh");
    if display_script.is_file() {
        let display_arg = ctx.args.display.clone().unwrap_or_else(|| {
            if ctx.profile == "ground_station" {
                "auto".to_string()
            } else {
                "none".to_string()
            }
        });
        let script_s = display_script.to_string_lossy();
        tracing::info!(display = %display_arg, "running display overlay installer");
        if !exec::run_ok(&script_s, &["--display", &display_arg]) {
            tracing::warn!("display overlay install returned non-zero (best-effort)");
        }
    } else {
        tracing::warn!("display overlay installer not found; skipping display provisioning");
    }

    // ── Camera ── operator-gated auto-enable: only auto when --camera given.
    let camera_script = source.join("scripts/drivers/install-camera-overlay.sh");
    if camera_script.is_file() {
        let camera_arg = ctx
            .args
            .camera
            .clone()
            .unwrap_or_else(|| "none".to_string());
        let script_s = camera_script.to_string_lossy();
        tracing::info!(camera = %camera_arg, "running camera overlay installer");
        if !exec::run_ok(&script_s, &["--camera", &camera_arg]) {
            tracing::warn!("camera overlay install returned non-zero (best-effort)");
        }
    } else {
        tracing::warn!("camera overlay installer not found; skipping camera provisioning");
    }
}

/// Operator-facing note explaining how to revert the radio services to the
/// packaged Python implementations. Deployed at `/etc/ados/CUTOVER`.
const CUTOVER_NOTE_PATH: &str = "/etc/ados/CUTOVER";

/// The body of the CUTOVER note (pure). The WFB transmit plane and the
/// ground direct-role receive plane are native-only (their packaged
/// predecessor was deleted). Only the mesh relay and receiver roles keep a
/// packaged fallback behind a flag file; the note tells an operator how to
/// flip those back.
pub fn cutover_note_body() -> &'static str {
    "ADOS radio services run native binaries.\n\
\n\
The drone transmit plane and the ground direct-role receive plane are\n\
native-only — there is no Python fallback for them.\n\
\n\
The mesh relay and receiver roles keep a packaged Python implementation as\n\
an emergency fallback. To revert a mesh role to Python, create the fallback\n\
flag and restart its unit:\n\
\n\
  touch /etc/ados/groundlink-python-fallback\n\
  systemctl restart ados-wfb-relay ados-wfb-receiver\n\
\n\
Remove the flag file and restart the unit to return to the native binary.\n"
}

/// Deploy the operator CUTOVER note at `/etc/ados/CUTOVER`. Idempotent overwrite
/// — the text is stable across reinstalls. Best-effort: a write failure only
/// loses the note, it never aborts the install.
fn write_cutover_note() {
    let path = Path::new(CUTOVER_NOTE_PATH);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Err(e) = std::fs::write(path, cutover_note_body()) {
        tracing::warn!(error = %e, "writing CUTOVER note failed");
        return;
    }
    set_mode(path, 0o644);
    tracing::info!("radio cutover note written");
}

/// Plugin trust keys dir under /etc/ados.
const PLUGIN_KEYS_DIR: &str = "/etc/ados/plugin-keys";
/// Peripheral seed manifests dir under /etc/ados.
const PERIPHERALS_DIR: &str = "/etc/ados/peripherals";

/// Provision the first-party plugin trust keys at `/etc/ados/plugin-keys/` so
/// the agent can verify signed `.adosplug` archives against the
/// `FIRST_PARTY_SIGNERS` allowlist. Ports 09-config.sh `provision_plugin_keys`:
/// copy every `*.pem` from `<source>/scripts/plugin-keys/` (the keys ship in the
/// repo and the Rust installer clones to `/opt/ados/source`, so they are always
/// on disk). Idempotent overwrite — the key bytes are stable across reinstalls.
///
/// This closes an install/uninstall asymmetry: the dir was created but the keys
/// were never copied, so a fresh Rust install could not verify any signed plugin.
fn provision_plugin_keys(source: Option<&Path>) {
    let _ = std::fs::create_dir_all(PLUGIN_KEYS_DIR);
    set_mode(Path::new(PLUGIN_KEYS_DIR), 0o700);
    let src_dir = match source.map(|s| s.join("scripts/plugin-keys")) {
        Some(p) if p.is_dir() => p,
        _ => {
            tracing::warn!("plugin-keys source dir not found; skipping trust-key provisioning");
            return;
        }
    };
    let read = match std::fs::read_dir(&src_dir) {
        Ok(r) => r,
        Err(_) => return,
    };
    let mut copied = 0usize;
    for entry in read.flatten() {
        let path = entry.path();
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) if n.ends_with(".pem") => n.to_string(),
            _ => continue,
        };
        let dst = Path::new(PLUGIN_KEYS_DIR).join(&name);
        if std::fs::copy(&path, &dst).is_ok() {
            set_mode(&dst, 0o600);
            copied += 1;
        }
    }
    tracing::info!(count = copied, "first-party plugin trust keys provisioned");
}

/// Seed the default BOM peripheral manifests at `/etc/ados/peripherals/` so the
/// webapp Peripherals page renders the FC, GPS, radio, OLED, SPI LCD, and camera
/// entries on a fresh board. Ports 09-config.sh `seed_default_peripherals`:
/// copy every `*.yaml` from `<source>/scripts/peripherals-seed/`, but PRESERVE
/// operator-edited files — a target is only overwritten when it is clearly one of
/// our shipped seeds (`id: ados.` on the first matching line) and the bytes
/// differ. Operator-added manifests (any non-`ados.` id) are never trampled.
fn seed_default_peripherals(source: Option<&Path>) {
    let _ = std::fs::create_dir_all(PERIPHERALS_DIR);
    set_mode(Path::new(PERIPHERALS_DIR), 0o755);
    let src_dir = match source.map(|s| s.join("scripts/peripherals-seed")) {
        Some(p) if p.is_dir() => p,
        _ => {
            tracing::warn!("peripherals-seed source dir not found; skipping seed manifests");
            return;
        }
    };
    let read = match std::fs::read_dir(&src_dir) {
        Ok(r) => r,
        Err(_) => return,
    };
    let mut copied = 0usize;
    let mut refreshed = 0usize;
    for entry in read.flatten() {
        let path = entry.path();
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) if n.ends_with(".yaml") => n.to_string(),
            _ => continue,
        };
        let target = Path::new(PERIPHERALS_DIR).join(&name);
        let seed_bytes = match std::fs::read(&path) {
            Ok(b) => b,
            Err(_) => continue,
        };
        if !target.exists() {
            if std::fs::write(&target, &seed_bytes).is_ok() {
                set_mode(&target, 0o644);
                copied += 1;
            }
        } else if target_is_ados_seed(&target) {
            let existing = std::fs::read(&target).unwrap_or_default();
            if existing != seed_bytes && std::fs::write(&target, &seed_bytes).is_ok() {
                set_mode(&target, 0o644);
                refreshed += 1;
            }
        }
    }
    tracing::info!(copied, refreshed, "default peripheral manifests seeded");
}

/// True when a target manifest declares an `id: ados.` (our shipped seed) on a
/// non-comment line — the overwrite gate that preserves operator-added files.
/// Mirrors the bash `grep -q '^id:[[:space:]]*ados\.'`.
fn target_is_ados_seed(target: &Path) -> bool {
    let body = match std::fs::read_to_string(target) {
        Ok(b) => b,
        Err(_) => return false,
    };
    first_line_declares_ados_id(&body)
}

/// Pure: does any line declare `id: ados.<...>` (leading whitespace then `id:`,
/// optional whitespace, then the `ados.` prefix)? Mirrors the bash grep.
pub fn first_line_declares_ados_id(body: &str) -> bool {
    for raw in body.lines() {
        let line = raw.trim_start();
        if let Some(rest) = line.strip_prefix("id:") {
            return rest.trim_start().starts_with("ados.");
        }
    }
    false
}

/// Operator config + agent identity provisioning.
pub struct ConfigIdentity;

impl Step for ConfigIdentity {
    fn id(&self) -> &str {
        "config_identity"
    }
    fn requires(&self) -> &[&str] {
        &["venv_agent"]
    }
    fn checkpoint(&self) -> Option<&str> {
        None
    }
    fn kind(&self) -> StepKind {
        StepKind::Required
    }
    fn run(&self, ctx: &mut Ctx) -> StepOutcome {
        // 1. Device id (required: identity is the install's keystone).
        let device_id = match ensure_device_id() {
            Ok(id) => id,
            Err(e) => return StepOutcome::Failed(format!("could not mint device id: {e}")),
        };
        let short_id: String = device_id.chars().take(8).collect();

        // 2. Persist the resolved profile + the default config.
        write_profile_conf(&ctx.profile);
        write_default_config(&short_id, ctx.args.name.as_deref(), &ctx.profile);

        // 3. Hostname (only when --name given).
        if let Some(name) = ctx.args.name.clone() {
            set_hostname(&name);
        }

        // 4. Pairing material (only when --pair given).
        if let Some(code) = ctx.args.pair.clone() {
            write_pairing(&code);
        }

        // 5. Delegate the brick-safe overlay provisioning to the driver scripts.
        let source = env::resolve_source_dir(ctx.source_dir.as_deref());
        provision_overlays(ctx, source.as_deref());

        // 6. Provision the first-party plugin trust keys (so signed plugins can
        //    be verified) and seed the default peripheral manifests (so the
        //    Peripherals page renders on a fresh board). Both copy from the
        //    cloned source tree; idempotent + operator-state-preserving.
        provision_plugin_keys(source.as_deref());
        seed_default_peripherals(source.as_deref());

        // 7. Deploy the operator note describing how to revert the radio
        //    services to the packaged Python fallback.
        write_cutover_note();

        StepOutcome::Ok
    }
}

/// Seconds since the Unix epoch.
fn now_epoch() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// chmod (Unix); a no-op on a non-Unix dev host.
#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode));
}

#[cfg(not(unix))]
fn set_mode(_path: &Path, _mode: u32) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugify_lowercases_and_collapses() {
        assert_eq!(slugify_hostname("My Drone 01"), "my-drone-01");
        assert_eq!(slugify_hostname("ALPHA__beta"), "alpha-beta");
        assert_eq!(slugify_hostname("--lead-and-trail--"), "lead-and-trail");
        assert_eq!(slugify_hostname("skynode"), "skynode");
    }

    #[test]
    fn slugify_caps_at_63_and_trims_dash() {
        let long = "a".repeat(70);
        let slug = slugify_hostname(&long);
        assert_eq!(slug.len(), 63);
        // A name whose 63rd char region is a dash must not leave a trailing '-'.
        let dashy = format!("{}-x", "b".repeat(62));
        let s = slugify_hostname(&dashy);
        assert!(!s.ends_with('-'), "slug must not end with '-': {s}");
        assert_eq!(s.len(), 62);
    }

    #[test]
    fn slugify_all_disallowed_is_empty() {
        assert_eq!(slugify_hostname("@@@"), "");
        assert_eq!(slugify_hostname(""), "");
    }

    #[test]
    fn default_config_carries_identity_and_blocks() {
        let cfg = default_config_yaml("abcd1234", "skynode", "drone", "/dev/ttyACM0");
        assert!(cfg.contains("device_id: \"abcd1234\""));
        assert!(cfg.contains("name: \"skynode\""));
        assert!(cfg.contains("profile: \"drone\""));
        assert!(cfg.contains("serial_port: \"/dev/ttyACM0\""));
        // The scripting REST block must keep port 8080 (the health gate probes it).
        assert!(cfg.contains("port: 8080"));
        // The pairing convex_url must be the constant, not blank.
        assert!(cfg.contains(&format!("convex_url: \"{CONVEX_URL}\"")));
        // Video defaults present.
        assert!(cfg.contains("bitrate_kbps: 4000"));
    }

    #[test]
    fn default_config_empty_fc_port_is_blank_string() {
        let cfg = default_config_yaml("abcd1234", "ados-abcd1234", "ground_station", "");
        assert!(cfg.contains("serial_port: \"\""));
        assert!(cfg.contains("profile: \"ground_station\""));
    }

    #[test]
    fn pairing_json_uppercases_and_stamps() {
        let body = pairing_json("abcd-1234", 1700000000);
        assert!(body.contains("\"pairing_code\": \"ABCD-1234\""));
        assert!(body.contains("\"code_created_at\": 1700000000"));
    }

    #[test]
    fn cutover_note_documents_only_the_mesh_fallback() {
        let body = cutover_note_body();
        // The drone transmit plane and the ground direct-role receive plane
        // are native-only: their fallback flag and unit must NOT appear.
        assert!(!body.contains("/etc/ados/wfb-python-fallback"));
        assert!(!body.contains("ados-wfb-rx"));
        // The mesh relay/receiver roles keep their packaged fallback.
        assert!(body.contains("/etc/ados/groundlink-python-fallback"));
        assert!(body.contains("ados-wfb-relay"));
        assert!(body.contains("ados-wfb-receiver"));
        // It must state the services run native binaries.
        assert!(body.to_lowercase().contains("native"));
        // No stale rust-enabled opt-in flag should leak into the operator note.
        assert!(!body.contains("rust-enabled"));
    }

    #[test]
    fn profile_conf_body_is_yaml_line() {
        assert_eq!(
            profile_conf_body("ground_station"),
            "profile: ground_station\n"
        );
    }

    #[test]
    fn hosts_rewrite_replaces_existing_127_0_1_1() {
        let hosts = "127.0.0.1\tlocalhost\n127.0.1.1\told-name\n::1\tlocalhost\n";
        let out = rewrite_hosts_body(hosts, "skynode");
        assert!(out.contains("127.0.1.1\tskynode"));
        assert!(!out.contains("old-name"));
        // The other lines survive.
        assert!(out.contains("127.0.0.1\tlocalhost"));
        assert!(out.contains("::1\tlocalhost"));
    }

    #[test]
    fn hosts_rewrite_appends_when_absent() {
        let hosts = "127.0.0.1\tlocalhost\n";
        let out = rewrite_hosts_body(hosts, "groundnode");
        assert!(out.contains("127.0.1.1\tgroundnode"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn ados_seed_id_is_detected_and_operator_files_are_preserved() {
        // A shipped seed (id: ados.<...>) is overwriteable.
        assert!(first_line_declares_ados_id(
            "name: Flight Controller\nid: ados.flight-controller\n"
        ));
        assert!(first_line_declares_ados_id("id:ados.gps\n"));
        assert!(first_line_declares_ados_id("id:   ados.radio\n"));
        // An operator-added manifest (non-ados id, or no id) is preserved.
        assert!(!first_line_declares_ados_id("id: custom.thing\n"));
        assert!(!first_line_declares_ados_id("name: Thing\nvendor: acme\n"));
        assert!(!first_line_declares_ados_id(""));
        // A commented-out id line is not a real declaration.
        assert!(!first_line_declares_ados_id(
            "# id: ados.commented\nid: custom.real\n"
        ));
    }
}
