//! Hardware watchdog arming at install time.
//!
//! A self-managed radio bind churn can hard-lock the kernel on some SoCs (the
//! RK3588 class is a known offender): every interface — USB radios AND the
//! on-SoC ethernet — goes dark at once with no clean shutdown, and the box stays
//! stranded until someone physically power-cycles it. No agent software can
//! recover a frozen kernel; the only thing that can is the SoC hardware watchdog.
//!
//! This step arms `/dev/watchdog` through systemd's `RuntimeWatchdogSec`: PID 1
//! pets the device on a timer, and if the kernel freezes (PID 1 can no longer
//! pet it) the SoC auto-resets and the box reboots itself — coming back on its
//! pinned MAC, no cable or manual power-cycle. `RebootWatchdogSec` covers the
//! second-order case where a reboot/shutdown itself hangs.
//!
//! Gated on the watchdog device actually existing (a VM or a board without one
//! is a clean no-op) and on the `network.watchdog.enabled` config (default-on).
//! Optional: a write/re-exec problem degrades, never aborts the install. Runs
//! after `deps` so the apt systemd upgrade (which does its own re-exec) is done.

use std::path::Path;

use serde::Deserialize;

use crate::ctx::Ctx;
use crate::env::CONFIG_YAML;
use crate::exec;
use crate::graph::{Step, StepKind, StepOutcome};

/// The SoC watchdog character device. Its presence is the hardware gate.
const WATCHDOG_DEV: &str = "/dev/watchdog";
/// The systemd manager drop-in this step writes.
const CONF_PATH: &str = "/etc/systemd/system.conf.d/ados-watchdog.conf";
/// How long PID 1 may be unresponsive before the SoC resets. systemd pets at
/// half this interval. Conservative enough not to false-trip a busy-but-alive
/// box (PID 1 stays schedulable under subprocess load); systemd clamps it down
/// if the hardware's max timeout is shorter.
const RUNTIME_SEC: &str = "30s";
/// How long a reboot/shutdown itself may hang before the SoC force-resets.
const REBOOT_SEC: &str = "2min";

/// The `config.yaml` slice this step reads. Everything optional so a config with
/// no `network.watchdog` block resolves to the default-on posture.
#[derive(Debug, Deserialize, Default)]
struct RootView {
    #[serde(default)]
    network: Option<NetworkView>,
}
#[derive(Debug, Deserialize, Default)]
struct NetworkView {
    #[serde(default)]
    watchdog: Option<WatchdogView>,
}
#[derive(Debug, Deserialize, Default)]
struct WatchdogView {
    #[serde(default)]
    enabled: Option<bool>,
}

/// True unless the config explicitly disables the watchdog. Default-on: a fresh
/// box with no `network.watchdog` block arms it. Pure so it is unit-tested
/// without the filesystem.
fn watchdog_enabled(text: &str) -> bool {
    serde_norway::from_str::<RootView>(text)
        .ok()
        .and_then(|r| r.network)
        .and_then(|n| n.watchdog)
        .and_then(|w| w.enabled)
        .unwrap_or(true)
}

/// Render the systemd `system.conf` drop-in that arms the hardware watchdog.
/// Pure.
fn render_conf() -> String {
    format!(
        "# ADOS Drone Agent — hardware watchdog.\n\
         # Arms the SoC watchdog so a kernel hard-lockup auto-reboots the box\n\
         # instead of stranding it. Generated by the agent; do not edit by hand.\n\
         [Manager]\n\
         RuntimeWatchdogSec={RUNTIME_SEC}\n\
         RebootWatchdogSec={REBOOT_SEC}\n"
    )
}

/// Hardware-watchdog arming step.
pub struct Watchdog;

impl Step for Watchdog {
    fn id(&self) -> &str {
        "watchdog"
    }
    fn requires(&self) -> &[&str] {
        // After deps so the apt systemd upgrade (its own daemon-reexec) is done
        // and won't clobber our drop-in.
        &["deps"]
    }
    fn checkpoint(&self) -> Option<&str> {
        // No checkpoint: re-affirm the drop-in on every upgrade.
        None
    }
    fn kind(&self) -> StepKind {
        // Optional: a write/re-exec problem must degrade, never abort the install.
        StepKind::Optional
    }
    fn run(&self, _ctx: &mut Ctx) -> StepOutcome {
        // No watchdog device → nothing to arm (a VM or a board without one).
        if !Path::new(WATCHDOG_DEV).exists() {
            tracing::info!("no hardware watchdog device present; skipping");
            return StepOutcome::Ok;
        }
        let enabled = std::fs::read_to_string(CONFIG_YAML)
            .map(|t| watchdog_enabled(&t))
            .unwrap_or(true);
        let path = Path::new(CONF_PATH);
        if !enabled {
            // Remove a previously-written drop-in + re-exec so the disable takes.
            if path.exists() {
                let _ = std::fs::remove_file(path);
                let _ = exec::run("systemctl", &["daemon-reexec"]);
            }
            tracing::info!("hardware watchdog disabled by config");
            return StepOutcome::Ok;
        }
        let body = render_conf();
        // Idempotent: skip the write + re-exec when the drop-in is already current.
        if std::fs::read_to_string(path)
            .map(|c| c == body)
            .unwrap_or(false)
        {
            tracing::info!("hardware watchdog drop-in already current");
            return StepOutcome::Ok;
        }
        if let Err(e) = write_file(path, &body) {
            tracing::warn!(error = %e, "failed to write hardware watchdog drop-in");
            return StepOutcome::Failed(format!("could not write {CONF_PATH}: {e}"));
        }
        // Re-exec PID 1 so it re-reads system.conf and opens /dev/watchdog at the
        // configured timeout. A plain daemon-reload does NOT re-read system.conf.
        let r = exec::run("systemctl", &["daemon-reexec"]);
        if !r.spawned || r.code != Some(0) {
            tracing::warn!(code = ?r.code, "daemon-reexec after watchdog write returned non-zero");
        }
        tracing::info!(
            runtime = RUNTIME_SEC,
            reboot = REBOOT_SEC,
            "armed the hardware watchdog"
        );
        StepOutcome::Ok
    }
}

/// Write `body` to `path` atomically (tmp + rename), creating the parent dir.
fn write_file(path: &Path, body: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("conf.tmp");
    std::fs::write(&tmp, body.as_bytes())?;
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_enables_watchdog() {
        assert!(watchdog_enabled(""));
        assert!(watchdog_enabled("agent:\n  name: x\n"));
        // An unrelated network block still defaults the watchdog on.
        assert!(watchdog_enabled(
            "network:\n  regulatory:\n    mode: region\n"
        ));
    }

    #[test]
    fn explicit_disable_is_honored() {
        assert!(!watchdog_enabled(
            "network:\n  watchdog:\n    enabled: false\n"
        ));
    }

    #[test]
    fn explicit_enable_is_honored() {
        assert!(watchdog_enabled(
            "network:\n  watchdog:\n    enabled: true\n"
        ));
    }

    #[test]
    fn conf_body_has_manager_section_and_both_timeouts() {
        let b = render_conf();
        assert!(b.starts_with("# ADOS Drone Agent"));
        assert!(b.contains("[Manager]"));
        assert!(b.contains("RuntimeWatchdogSec=30s"));
        assert!(b.contains("RebootWatchdogSec=2min"));
        assert!(b.ends_with('\n'));
    }
}
