"""Pydantic request models for ground-station route bodies.

Holding all request models in one file matches the import patterns of
the route sub-modules (most do
``from ados.api.routes.ground_station._common import (PairRequest,
WfbUpdate)``) and avoids one tiny file per model.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class WfbUpdate(BaseModel):
    """PUT body for the ground-station WFB radio config."""

    channel: int | None = None
    bitrate_profile: str | None = None
    fec: str | None = None


class PairRequest(BaseModel):
    """POST body for cloud-relay pair-key install on the GS side.

    ``blob_b64`` is a base64-encoded 64-byte wfb-ng key file (rx-side,
    libsodium crypto_box format, generated by ``wfb_keygen``). The
    typed-string ``pair_key`` field is kept for compatibility with old
    GCS clients that try to pass a hex/base58 secret; it is ignored
    when ``blob_b64`` is present and rejected with a 400 otherwise.
    """

    blob_b64: str | None = Field(default=None)
    drone_device_id: str | None = None
    # Kept so old clients fail with a clear 400 rather than a 422.
    pair_key: str | None = None


class OledUpdate(BaseModel):
    """PUT body for OLED UI settings.

    Server and OLED both use the 0-255 native contrast scale, which
    matches the display hardware register range and the GCS slider range.
    """

    brightness: int | None = Field(default=None, ge=0, le=255)
    auto_dim_enabled: bool | None = None
    screen_cycle_seconds: int | None = Field(default=None, ge=1, le=60)


class ButtonsUpdate(BaseModel):
    """PUT body for button remap. Opaque dict of action bindings."""

    mapping: dict[str, str] | None = None


class ScreensUpdate(BaseModel):
    """PUT body for screen order + enabled list."""

    order: list[str] | None = None
    enabled: list[str] | None = None


class BluetoothScanRequest(BaseModel):
    """POST body for the Bluetooth scan endpoint."""

    duration_s: int | None = Field(default=None, ge=1, le=60)


class BluetoothPairRequest(BaseModel):
    """POST body for Bluetooth pairing."""

    mac: str = Field(..., min_length=1)


class GamepadPrimaryUpdate(BaseModel):
    """PUT body for primary-gamepad selection."""

    device_id: str = Field(..., min_length=1)


class PicClaimRequest(BaseModel):
    """POST body for PIC claim."""

    client_id: str = Field(..., min_length=1)
    confirm_token: str | None = None
    force: bool | None = False


class PicReleaseRequest(BaseModel):
    """POST body for PIC release."""

    client_id: str = Field(..., min_length=1)


class PicConfirmTokenRequest(BaseModel):
    """POST body for PIC confirm-token mint."""

    client_id: str = Field(..., min_length=1)


class PicHeartbeatRequest(BaseModel):
    """POST body for PIC session heartbeat."""

    client_id: str = Field(..., min_length=1)


class WifiJoinRequest(BaseModel):
    """PUT body for /network/client/join."""

    ssid: str = Field(..., min_length=1)
    passphrase: str | None = None
    force: bool | None = False


class RoleChangeRequest(BaseModel):
    role: Literal["direct", "relay", "receiver"]
    confirm_token: str | None = None


class MeshConfigUpdate(BaseModel):
    mesh_id: str | None = None
    carrier: Literal["802.11s", "ibss"] | None = None
    channel: int | None = Field(default=None, ge=1, le=13)


class MeshGatewayPreferenceUpdate(BaseModel):
    mode: Literal["auto", "pinned", "off"]
    pinned_mac: str | None = None


class PairAcceptRequest(BaseModel):
    duration_s: int = Field(default=60, ge=5, le=300)


class PairApproveRequest(BaseModel):
    device_id: str


class PairRevokeRequest(BaseModel):
    device_id: str


class PairJoinRequest(BaseModel):
    receiver_host: str | None = None
    receiver_port: int | None = Field(default=None, ge=1, le=65535)


__all__ = [
    "WfbUpdate",
    "PairRequest",
    "OledUpdate",
    "ButtonsUpdate",
    "ScreensUpdate",
    "BluetoothScanRequest",
    "BluetoothPairRequest",
    "GamepadPrimaryUpdate",
    "PicClaimRequest",
    "PicReleaseRequest",
    "PicConfirmTokenRequest",
    "PicHeartbeatRequest",
    "WifiJoinRequest",
    "RoleChangeRequest",
    "MeshConfigUpdate",
    "MeshGatewayPreferenceUpdate",
    "PairAcceptRequest",
    "PairApproveRequest",
    "PairRevokeRequest",
    "PairJoinRequest",
]
