"""Pydantic request models for ground-station route bodies.

Holding all request models in one file matches the import patterns of
the route sub-modules (most do
``from ados.api.routes.ground_station._common import (PairRequest,
WfbUpdate)``) and avoids one tiny file per model.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator

from .validators import _validate_ipv4, _validate_ipv4_cidr


class WfbUpdate(BaseModel):
    """PUT body for the ground-station WFB radio config."""

    channel: int | None = None
    bitrate_profile: str | None = None
    fec: str | None = None


class ApUpdate(BaseModel):
    """PUT body for the AP subsection of network config."""

    enabled: bool | None = None
    ssid: str | None = None
    passphrase: str | None = None
    channel: int | None = None


class PairRequest(BaseModel):
    """POST body for cloud-relay pair-key install on the GS side.

    ``blob_b64`` is a base64-encoded 64-byte wfb-ng key file (rx-side,
    libsodium crypto_box format, generated by ``wfb_keygen``). The
    typed-string ``pair_key`` field is kept for compatibility with old
    GCS clients that try to pass a hex/base58 secret; it is ignored
    when ``blob_b64`` is present and rejected with a 400 otherwise.
    """

    blob_b64: str | None = Field(default=None)
    drone_device_id: str | None = None
    # Kept so old clients fail with a clear 400 rather than a 422.
    pair_key: str | None = None


class OledUpdate(BaseModel):
    """PUT body for OLED UI settings.

    Server and OLED both use the 0-255 native contrast scale, which
    matches the display hardware register range and the GCS slider range.
    """

    brightness: int | None = Field(default=None, ge=0, le=255)
    auto_dim_enabled: bool | None = None
    screen_cycle_seconds: int | None = Field(default=None, ge=1, le=60)


class ButtonsUpdate(BaseModel):
    """PUT body for button remap. Opaque dict of action bindings."""

    mapping: dict[str, str] | None = None


class ScreensUpdate(BaseModel):
    """PUT body for screen order + enabled list."""

    order: list[str] | None = None
    enabled: list[str] | None = None


class DisplayUpdate(BaseModel):
    """PUT body for HDMI kiosk display config."""

    resolution: str | None = Field(default=None)
    kiosk_enabled: bool | None = None
    kiosk_target_url: str | None = None


class BluetoothScanRequest(BaseModel):
    """POST body for the Bluetooth scan endpoint."""

    duration_s: int | None = Field(default=None, ge=1, le=60)


class BluetoothPairRequest(BaseModel):
    """POST body for Bluetooth pairing."""

    mac: str = Field(..., min_length=1)


class GamepadPrimaryUpdate(BaseModel):
    """PUT body for primary-gamepad selection."""

    device_id: str = Field(..., min_length=1)


class PicClaimRequest(BaseModel):
    """POST body for PIC claim."""

    client_id: str = Field(..., min_length=1)
    confirm_token: str | None = None
    force: bool | None = False


class PicReleaseRequest(BaseModel):
    """POST body for PIC release."""

    client_id: str = Field(..., min_length=1)


class PicConfirmTokenRequest(BaseModel):
    """POST body for PIC confirm-token mint."""

    client_id: str = Field(..., min_length=1)


class PicHeartbeatRequest(BaseModel):
    """POST body for PIC session heartbeat."""

    client_id: str = Field(..., min_length=1)


class WifiJoinRequest(BaseModel):
    """PUT body for /network/client/join."""

    ssid: str = Field(..., min_length=1)
    passphrase: str | None = None
    force: bool | None = False


class ModemConfigUpdate(BaseModel):
    """PUT body for /network/modem.

    The GET view reports the cap as ``cap_mb`` (megabytes), so a client that
    round-trips the view sends ``cap_mb`` back. The route accepts either:
    ``cap_gb`` wins when both are present, otherwise ``cap_mb`` is converted to
    ``cap_gb`` before it reaches the manager (which persists in GB).
    """

    apn: str | None = None
    cap_gb: float | None = Field(default=None, gt=0, le=9223372036.0)
    cap_mb: int | None = Field(default=None, gt=0)
    enabled: bool | None = None


class UplinkPriorityUpdate(BaseModel):
    """PUT body for /network/priority."""

    priority: list[str] = Field(..., min_length=1)


class ShareUplinkUpdate(BaseModel):
    """PUT body for /network/share_uplink."""

    enabled: bool


class RoleChangeRequest(BaseModel):
    role: Literal["direct", "relay", "receiver"]
    confirm_token: str | None = None


class MeshConfigUpdate(BaseModel):
    mesh_id: str | None = None
    carrier: Literal["802.11s", "ibss"] | None = None
    channel: int | None = Field(default=None, ge=1, le=13)


class MeshGatewayPreferenceUpdate(BaseModel):
    mode: Literal["auto", "pinned", "off"]
    pinned_mac: str | None = None


class PairAcceptRequest(BaseModel):
    duration_s: int = Field(default=60, ge=5, le=300)


class PairApproveRequest(BaseModel):
    device_id: str


class PairRevokeRequest(BaseModel):
    device_id: str


class PairJoinRequest(BaseModel):
    receiver_host: str | None = None
    receiver_port: int | None = Field(default=None, ge=1, le=65535)


class EthernetConfigUpdate(BaseModel):
    """PUT body for /network/ethernet."""

    mode: Literal["dhcp", "static"]
    ip: str | None = None
    gateway: str | None = None
    dns: list[str] | None = None

    @field_validator("ip")
    @classmethod
    def _v_ip(cls, v: str | None) -> str | None:
        if v is None or v == "":
            return None
        if not _validate_ipv4_cidr(v):
            raise ValueError("ip must be IPv4 with CIDR suffix, e.g. 192.168.1.42/24")
        return v

    @field_validator("gateway")
    @classmethod
    def _v_gateway(cls, v: str | None) -> str | None:
        if v is None or v == "":
            return None
        if not _validate_ipv4(v):
            raise ValueError("gateway must be a valid IPv4 address")
        return v

    @field_validator("dns")
    @classmethod
    def _v_dns(cls, v: list[str] | None) -> list[str] | None:
        if v is None:
            return None
        for entry in v:
            if not _validate_ipv4(entry):
                raise ValueError(f"dns entry {entry!r} is not a valid IPv4 address")
        return v


__all__ = [
    "WfbUpdate",
    "ApUpdate",
    "PairRequest",
    "OledUpdate",
    "ButtonsUpdate",
    "ScreensUpdate",
    "DisplayUpdate",
    "BluetoothScanRequest",
    "BluetoothPairRequest",
    "GamepadPrimaryUpdate",
    "PicClaimRequest",
    "PicReleaseRequest",
    "PicConfirmTokenRequest",
    "PicHeartbeatRequest",
    "WifiJoinRequest",
    "ModemConfigUpdate",
    "UplinkPriorityUpdate",
    "ShareUplinkUpdate",
    "RoleChangeRequest",
    "MeshConfigUpdate",
    "MeshGatewayPreferenceUpdate",
    "PairAcceptRequest",
    "PairApproveRequest",
    "PairRevokeRequest",
    "PairJoinRequest",
    "EthernetConfigUpdate",
]
