//! Key derivation + AEAD for WFB-ng broadcast payloads.
//!
//! The WFB-ng wire format pre-shares a 32-byte symmetric key between the
//! air-side and the ground-side. Operators supply a passphrase via the
//! setup webapp; both sides derive the same 32-byte key from it so a
//! ground decoder seeded with the same passphrase can authenticate the
//! frames coming from the air encoder without the key ever crossing the
//! wire.
//!
//! # Algorithm
//!
//! Matches the WFB-ng project documented passphrase-to-key flow:
//!
//! 1. `seed = SHA-256(passphrase_utf8)` — 32 bytes, deterministic.
//! 2. `secret = x25519_dalek::StaticSecret::from(seed)` — clamps the seed
//!    to a valid Curve25519 scalar.
//! 3. `shared = secret.diffie_hellman(&FIXED_PEER_PUBLIC_KEY)` — X25519
//!    against a documented peer. The peer is a build-time constant so
//!    air + ground agree without exchanging anything online.
//! 4. `key = SHA-256(shared.as_bytes())` — 32 bytes, suitable for
//!    `ChaCha20Poly1305`.
//!
//! The output is pinned by the
//! [`derived_key_matches_kat`](tests::derived_key_matches_kat) and
//! [`key_fingerprint_kat`](tests::key_fingerprint_kat) known-answer
//! tests: any future regression of the KDF surface is caught at
//! `cargo test`. The KAT carries three independent vectors, each
//! generated by the in-tree implementation itself; the upstream wfb-ng
//! passphrase-to-key flow is a different algorithm with a different
//! output shape, so these vectors are drift detectors for ados-wfb
//! rather than parity vectors against any external oracle.

use chacha20poly1305::aead::{Aead, KeyInit};
use chacha20poly1305::{ChaCha20Poly1305, Nonce};
use rand_core::{OsRng, RngCore};
use sha2::{Digest, Sha256};
use thiserror::Error;
use x25519_dalek::{PublicKey, StaticSecret};

/// Length in bytes of the symmetric broadcast key.
pub const KEY_LEN: usize = 32;

/// Length in bytes of the per-frame nonce for ChaCha20-Poly1305.
pub const NONCE_LEN: usize = 12;

/// Length in bytes of a Curve25519 public key (the public component
/// returned by [`generate_keypair`] / [`regenerate_public_key_hex`]).
pub const PUBLIC_KEY_LEN: usize = 32;

/// Number of bytes generated for [`generate_passphrase`]. 24 bytes of
/// OS randomness encoded as 48 hex chars sits comfortably above the
/// 128-bit security floor without producing a passphrase the operator
/// cannot copy.
const FRESH_PASSPHRASE_BYTES: usize = 24;

/// Fixed peer Curve25519 public key. The bytes here are derived from a
/// documented seed (`SHA-256("ados-wfb-v0-fixed-peer")`) so the constant
/// carries no operator data and is reproducible without source
/// archaeology. Any future rotation lands as a single constant change
/// plus a re-pinned KAT in this module.
const FIXED_PEER_PUBLIC_KEY: [u8; 32] = [
    0x1b, 0x81, 0x4e, 0x49, 0x69, 0x1b, 0xe0, 0xd8, 0x23, 0xe0, 0x6f, 0xa1, 0xee, 0x75, 0x88, 0x07,
    0x78, 0x6c, 0x51, 0xde, 0xfc, 0x30, 0xa8, 0x67, 0x78, 0x01, 0x27, 0x28, 0x1f, 0xb9, 0x48, 0x78,
];

/// Errors that can surface from the key + AEAD layer.
#[derive(Debug, Error)]
pub enum KeyError {
    /// The supplied passphrase was empty. Distinct from the AEAD failures
    /// so the wizard can show "passphrase is required" vs "passphrase did
    /// not authenticate."
    #[error("passphrase must not be empty")]
    EmptyPassphrase,
    /// AEAD seal failed. ChaCha20-Poly1305 cannot fail on encrypt under
    /// normal conditions; a failure here means an out-of-memory or other
    /// host-level fault.
    #[error("aead seal failed")]
    SealFailed,
    /// AEAD open failed. The wrapper key did not authenticate, or the
    /// nonce was reused, or the ciphertext was truncated.
    #[error("aead open failed (key mismatch or tampered ciphertext)")]
    OpenFailed,
}

/// Derive a 32-byte symmetric key from `passphrase` using the algorithm
/// documented in this module's preamble.
pub fn derive_key(passphrase: &str) -> Result<[u8; KEY_LEN], KeyError> {
    if passphrase.is_empty() {
        return Err(KeyError::EmptyPassphrase);
    }

    // Step 1: seed = SHA-256(passphrase).
    let seed = sha256_bytes(passphrase.as_bytes());

    // Step 2: clamp the seed into a Curve25519 scalar.
    let secret = StaticSecret::from(seed);

    // Step 3: ECDH against the fixed peer.
    let peer = PublicKey::from(FIXED_PEER_PUBLIC_KEY);
    let shared = secret.diffie_hellman(&peer);

    // Step 4: SHA-256 the shared secret to produce the broadcast key.
    let key = sha256_bytes(shared.as_bytes());
    Ok(key)
}

/// Derive both the public and the symmetric broadcast key for a given
/// passphrase. The public component is what an operator records for
/// ground-side decoder seeding; the secret stays inside the agent
/// process. Returns `(public_key_bytes, broadcast_key_bytes)`.
pub fn derive_keypair(
    passphrase: &str,
) -> Result<([u8; PUBLIC_KEY_LEN], [u8; KEY_LEN]), KeyError> {
    if passphrase.is_empty() {
        return Err(KeyError::EmptyPassphrase);
    }
    let seed = sha256_bytes(passphrase.as_bytes());
    let secret = StaticSecret::from(seed);
    let public = PublicKey::from(&secret);
    let peer = PublicKey::from(FIXED_PEER_PUBLIC_KEY);
    let shared = secret.diffie_hellman(&peer);
    let broadcast = sha256_bytes(shared.as_bytes());
    Ok((public.to_bytes(), broadcast))
}

/// Generate a fresh, OS-entropy-backed passphrase suitable for handing
/// to [`derive_key`]. Used by the `regenerate-key` REST handler so an
/// operator can rotate the broadcast key from the wizard without typing
/// a new passphrase by hand.
///
/// Output is hex-encoded so it round-trips through any text channel an
/// operator may use to ferry it to the ground decoder.
pub fn generate_passphrase() -> String {
    let mut bytes = [0u8; FRESH_PASSPHRASE_BYTES];
    OsRng.fill_bytes(&mut bytes);
    hex_lower(&bytes)
}

/// Compute a fingerprint over a 32-byte key. Returns the first 8 bytes
/// of `SHA-256(key)` hex-encoded — short enough for a wizard banner,
/// long enough to disambiguate two keys at a glance. Used by the
/// regenerate-key REST surface so the operator sees a stable "key
/// fingerprint" without the secret leaking.
pub fn key_fingerprint(key: &[u8; KEY_LEN]) -> String {
    let digest = sha256_bytes(key);
    hex_lower(&digest[..8])
}

/// Return the public key for a passphrase as a hex string. Convenience
/// wrapper for the REST handler that mints fresh keys; never persists
/// the passphrase, only the derived public bytes.
pub fn regenerate_public_key_hex(passphrase: &str) -> Result<String, KeyError> {
    let (public, _broadcast) = derive_keypair(passphrase)?;
    Ok(hex_lower(&public))
}

/// Build a fresh keypair with random scalar (NOT derived from a
/// passphrase). Used when the operator wants the agent to mint and
/// persist the secret rather than supply a passphrase.
pub fn generate_keypair() -> ([u8; PUBLIC_KEY_LEN], [u8; KEY_LEN]) {
    let mut seed = [0u8; 32];
    OsRng.fill_bytes(&mut seed);
    let secret = StaticSecret::from(seed);
    let public = PublicKey::from(&secret);
    let peer = PublicKey::from(FIXED_PEER_PUBLIC_KEY);
    let shared = secret.diffie_hellman(&peer);
    let broadcast = sha256_bytes(shared.as_bytes());
    (public.to_bytes(), broadcast)
}

/// Seal `plaintext` under `key` with a per-call `nonce`. The caller is
/// responsible for ensuring the nonce is unique across calls under the
/// same key — WFB-ng generates per-frame nonces from a sequence number,
/// which the orchestration layer threads through here.
pub fn seal(key: &[u8; KEY_LEN], nonce: &[u8; NONCE_LEN], plaintext: &[u8]) -> Result<Vec<u8>, KeyError> {
    let cipher = ChaCha20Poly1305::new(key.into());
    let nonce = Nonce::from_slice(nonce);
    cipher
        .encrypt(nonce, plaintext)
        .map_err(|_| KeyError::SealFailed)
}

/// Open a ciphertext produced by [`seal`].
pub fn unseal(key: &[u8; KEY_LEN], nonce: &[u8; NONCE_LEN], ciphertext: &[u8]) -> Result<Vec<u8>, KeyError> {
    let cipher = ChaCha20Poly1305::new(key.into());
    let nonce = Nonce::from_slice(nonce);
    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|_| KeyError::OpenFailed)
}

fn sha256_bytes(input: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(input);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    out
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Same passphrase always produces the same key bytes. The whole
    /// air-ground key sharing scheme depends on this.
    #[test]
    fn derive_key_is_deterministic() {
        let a = derive_key("hunter2-correct-horse").unwrap();
        let b = derive_key("hunter2-correct-horse").unwrap();
        assert_eq!(a, b);
    }

    /// Different passphrases must yield different keys. A collision here
    /// would let an attacker who knew any common passphrase decrypt
    /// traffic from a different operator.
    #[test]
    fn derive_key_differs_per_passphrase() {
        let a = derive_key("alpha").unwrap();
        let b = derive_key("bravo").unwrap();
        assert_ne!(a, b);
    }

    /// Output is exactly 32 bytes — the contract `ChaCha20Poly1305` and
    /// the WFB-ng wire format both pin.
    #[test]
    fn derive_key_outputs_32_bytes() {
        let k = derive_key("any-non-empty-string").unwrap();
        assert_eq!(k.len(), 32);
    }

    /// Empty passphrase is a typed error, not a silent success that
    /// would derive a known key.
    #[test]
    fn derive_key_rejects_empty_passphrase() {
        match derive_key("") {
            Err(KeyError::EmptyPassphrase) => {}
            other => panic!("expected EmptyPassphrase, got {other:?}"),
        }
    }

    /// Round-trip: seal then unseal returns the original bytes.
    #[test]
    fn chacha_seal_unseal_roundtrip() {
        let key = derive_key("operator-passphrase").unwrap();
        let nonce = [0u8; NONCE_LEN];
        let payload = b"a sample h.264 NAL unit";
        let ct = seal(&key, &nonce, payload).unwrap();
        let pt = unseal(&key, &nonce, &ct).unwrap();
        assert_eq!(pt, payload);
    }

    /// Wrong-key open must fail. This is the property that makes the
    /// broadcast confidential against anyone without the passphrase.
    #[test]
    fn chacha_with_wrong_key_fails() {
        let key_a = derive_key("operator-a").unwrap();
        let key_b = derive_key("operator-b").unwrap();
        let nonce = [0u8; NONCE_LEN];
        let ct = seal(&key_a, &nonce, b"payload").unwrap();
        match unseal(&key_b, &nonce, &ct) {
            Err(KeyError::OpenFailed) => {}
            other => panic!("expected OpenFailed, got {other:?}"),
        }
    }

    /// Documents how the FIXED_PEER_PUBLIC_KEY constant was generated so
    /// any future rotation is reproducible without source archaeology.
    #[test]
    fn fixed_peer_constant_matches_documented_seed() {
        let expected = sha256_bytes(b"ados-wfb-v0-fixed-peer");
        assert_eq!(FIXED_PEER_PUBLIC_KEY, expected);
    }

    /// The three pinned passphrases that anchor the KAT block. Each
    /// vector cross-checks one independent code path:
    ///
    /// - **A** (`ados-wfb-kat-fixture-2026`): the original anchor; long
    ///   ASCII with hyphens.
    /// - **B** (`wfb-test-2026`): short ASCII; checks that nothing in the
    ///   pipeline silently relies on an input-length floor.
    /// - **C** (64 hex chars passed as UTF-8): looks like an entropy hex
    ///   string but is fed verbatim as a passphrase. Catches any future
    ///   change that starts hex-decoding the input behind the back of the
    ///   documented algorithm.
    ///
    /// The expected bytes for all three were generated by the in-tree
    /// implementation itself — the upstream wfb-ng KDF is a different
    /// algorithm (Argon2i + crypto_box keypairs over X25519) producing
    /// different output shape, so these vectors are drift detectors
    /// rather than parity vectors. The Rust implementation is the oracle
    /// for itself: regenerate the constants by running
    /// `cargo test -p ados-wfb -- --ignored kat_print --nocapture` after
    /// the next intentional algorithm change.
    const KAT_PASSPHRASE_A: &str = "ados-wfb-kat-fixture-2026";
    const KAT_PASSPHRASE_B: &str = "wfb-test-2026";
    const KAT_PASSPHRASE_C: &str =
        "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    /// Pinned bytes for [`KAT_PASSPHRASE_A`]. Generated by the documented
    /// KDF (SHA-256 → Curve25519 → ECDH against `FIXED_PEER_PUBLIC_KEY`
    /// → SHA-256 finalize). See [`derived_key_matches_kat`].
    const KAT_EXPECTED_A: [u8; 32] = [
        0xf2, 0x4a, 0xeb, 0x2b, 0x03, 0xb9, 0x4e, 0x31, 0xd3, 0xc1, 0xfb, 0x67, 0x5c, 0x0b, 0x51,
        0x15, 0xaf, 0x6d, 0x2c, 0x6c, 0x70, 0x02, 0x6e, 0xe2, 0x8b, 0x81, 0xa2, 0x15, 0xeb, 0xfc,
        0x32, 0x40,
    ];

    /// Pinned bytes for [`KAT_PASSPHRASE_B`]. Generated the same way as
    /// [`KAT_EXPECTED_A`].
    const KAT_EXPECTED_B: [u8; 32] = [
        0x66, 0x60, 0x08, 0x5c, 0x84, 0x0c, 0x7e, 0x5c, 0x64, 0x51, 0xee, 0xd2, 0x48, 0x26, 0x78,
        0xd6, 0x36, 0x0c, 0xe6, 0x25, 0xc1, 0x97, 0xd8, 0x5d, 0xb5, 0xd1, 0x6d, 0xb1, 0x61, 0x6e,
        0x8a, 0x1e,
    ];

    /// Pinned bytes for [`KAT_PASSPHRASE_C`]. Generated the same way as
    /// [`KAT_EXPECTED_A`].
    const KAT_EXPECTED_C: [u8; 32] = [
        0xfe, 0xc4, 0x26, 0x5a, 0xfc, 0x85, 0xa6, 0x5a, 0x1c, 0xe8, 0x54, 0x77, 0x71, 0x28, 0xf6,
        0xf5, 0xf9, 0x13, 0x5c, 0x91, 0x38, 0x28, 0x9d, 0x92, 0x98, 0x30, 0xe9, 0xce, 0xa1, 0x9d,
        0xeb, 0x30,
    ];

    /// Pinned fingerprints (first 8 bytes of `SHA-256(public_key)` hex)
    /// for each passphrase. Catches drift in the public-key surface or
    /// the fingerprint helper independently of the broadcast-key drift
    /// caught by [`derived_key_matches_kat`].
    const KAT_FINGERPRINT_A: &str = "167c191caacef7a4";
    const KAT_FINGERPRINT_B: &str = "fa4aae2615c5f196";
    const KAT_FINGERPRINT_C: &str = "4df5e139153ed20f";

    /// Known-answer test pinning the documented KDF output for three
    /// fixed passphrases. Any change to the key derivation algorithm —
    /// algorithm substitution, peer-constant rotation, hash function
    /// swap — surfaces here as a hard failure so the air + ground halves
    /// cannot drift silently. To re-pin (e.g., after a documented peer
    /// rotation), run `cargo test -p ados-wfb -- --ignored kat_print
    /// --nocapture`, copy the hex into the `KAT_EXPECTED_*` constants,
    /// and re-run.
    #[test]
    fn derived_key_matches_kat() {
        let key_a = derive_key(KAT_PASSPHRASE_A).expect("derive_key A");
        let key_b = derive_key(KAT_PASSPHRASE_B).expect("derive_key B");
        let key_c = derive_key(KAT_PASSPHRASE_C).expect("derive_key C");
        if std::env::var_os("ADOS_WFB_KAT_PRINT").is_some() {
            eprintln!("ADOS_WFB_KAT_A = {}", hex_lower(&key_a));
            eprintln!("ADOS_WFB_KAT_B = {}", hex_lower(&key_b));
            eprintln!("ADOS_WFB_KAT_C = {}", hex_lower(&key_c));
        }
        assert_eq!(
            key_a, KAT_EXPECTED_A,
            "KDF output for passphrase A drifted from pinned KAT bytes",
        );
        assert_eq!(
            key_b, KAT_EXPECTED_B,
            "KDF output for passphrase B drifted from pinned KAT bytes",
        );
        assert_eq!(
            key_c, KAT_EXPECTED_C,
            "KDF output for passphrase C drifted from pinned KAT bytes",
        );
    }

    /// Companion KAT that pins the fingerprint of the derived public key
    /// for each pinned passphrase. Independent of
    /// [`derived_key_matches_kat`] because the broadcast key and the
    /// public key are derived from disjoint sides of the X25519 pair —
    /// drift in either surface should fail loudly.
    #[test]
    fn key_fingerprint_kat() {
        for (label, passphrase, expected) in [
            ("A", KAT_PASSPHRASE_A, KAT_FINGERPRINT_A),
            ("B", KAT_PASSPHRASE_B, KAT_FINGERPRINT_B),
            ("C", KAT_PASSPHRASE_C, KAT_FINGERPRINT_C),
        ] {
            let (public, _broadcast) =
                derive_keypair(passphrase).expect("derive_keypair against fixture");
            let fp_bytes = sha256_bytes(&public);
            let fp = hex_lower(&fp_bytes[..8]);
            if std::env::var_os("ADOS_WFB_KAT_PRINT").is_some() {
                eprintln!("ADOS_WFB_FINGERPRINT_{label} = {fp}");
            }
            assert_eq!(
                fp, expected,
                "public-key fingerprint for passphrase {label} drifted from pinned KAT",
            );
        }
    }

    /// Print-only helper that emits the raw bytes for the three pinned
    /// passphrases. `#[ignore]` so it never runs in the default suite —
    /// invoke explicitly with `cargo test -p ados-wfb -- --ignored
    /// kat_print --nocapture` when re-pinning the KAT after an
    /// intentional algorithm change.
    #[test]
    #[ignore]
    fn kat_print() {
        for (label, passphrase) in [
            ("A", KAT_PASSPHRASE_A),
            ("B", KAT_PASSPHRASE_B),
            ("C", KAT_PASSPHRASE_C),
        ] {
            let key = derive_key(passphrase).expect("derive_key against fixture");
            let (public, _broadcast) =
                derive_keypair(passphrase).expect("derive_keypair against fixture");
            let fp_bytes = sha256_bytes(&public);
            let fp = hex_lower(&fp_bytes[..8]);
            eprintln!("--- KAT vector {label} ---");
            eprintln!("passphrase    = {passphrase:?}");
            eprintln!("derive_key    = {}", hex_lower(&key));
            eprintln!("public_key    = {}", hex_lower(&public));
            eprintln!("fingerprint   = {fp}");
        }
    }

    /// Generated passphrases are non-empty, hex-encoded, and unique
    /// across calls. Enough rigor that an operator triggering
    /// `regenerate-key` twice cannot land on the same key.
    #[test]
    fn generate_passphrase_is_random_hex() {
        let a = generate_passphrase();
        let b = generate_passphrase();
        assert_ne!(a, b, "generate_passphrase must not produce duplicates");
        assert!(!a.is_empty());
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
        assert_eq!(a.len(), FRESH_PASSPHRASE_BYTES * 2);
    }

    /// Fingerprint output is exactly 16 hex chars (8 bytes) and stable.
    #[test]
    fn key_fingerprint_is_eight_bytes_hex() {
        let key = derive_key("operator-passphrase").unwrap();
        let fp = key_fingerprint(&key);
        assert_eq!(fp.len(), 16);
        assert!(fp.chars().all(|c| c.is_ascii_hexdigit()));
        // Stable across calls.
        assert_eq!(fp, key_fingerprint(&key));
    }

    /// Public key extraction round-trips via the dedicated keypair path.
    #[test]
    fn derive_keypair_returns_public_and_broadcast() {
        let (pub_bytes, broadcast) = derive_keypair("hello-world").unwrap();
        assert_eq!(pub_bytes.len(), 32);
        assert_eq!(broadcast.len(), 32);
        // The same passphrase fed through the symmetric path produces
        // the same broadcast key.
        let only_broadcast = derive_key("hello-world").unwrap();
        assert_eq!(broadcast, only_broadcast);
    }

    /// Hex helper output is lowercase + correctly padded.
    #[test]
    fn hex_lower_pads_single_byte() {
        assert_eq!(hex_lower(&[0x0a, 0x05]), "0a05");
    }
}
