// @generated by ados-capabilities-codegen from contracts.toml. Do not edit by hand.
//! Generated IPC contract + sidecar version registry.
//!
//! One source of truth for every IPC wire-contract version integer
//! and every state-sidecar version, for Rust, Python, and TS.
//! Source: contracts.toml; run ados-capabilities-codegen.

/// Version and wire metadata for one IPC contract or state sidecar.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContractMeta {
    pub id: &'static str,
    pub version: u16,
    pub wire: &'static str,
    pub transport: &'static str,
    pub status: &'static str,
    pub description: &'static str,
}

/// Every versioned inter-process wire contract.
#[rustfmt::skip]
pub const CONTRACTS: &[ContractMeta] = &[
    ContractMeta { id: "plugin.rpc", version: 1, wire: "msgpack", transport: "unix-stream", status: "active", description: "Plugin RPC envelope: msgpack short-key request/response plus a pipe-delimited HMAC-SHA256 capability token." },  // ados_protocol::plugin::PROTOCOL_VERSION
    ContractMeta { id: "logd.ingest", version: 1, wire: "msgpack", transport: "unix-socket", status: "active", description: "Black-box ingest frames: logs, telemetry, discrete events, and hardware snapshots." },  // ados_protocol::logd::WIRE_VERSION
    ContractMeta { id: "logd.read", version: 1, wire: "json", transport: "http", status: "active", description: "Black-box read-API request and response envelope." },  // ados_protocol::logd::ENVELOPE_VERSION
    ContractMeta { id: "framebus.ring", version: 1, wire: "binary", transport: "shared-memory", status: "active", description: "Shared-memory vision frame ring layout: a header plus seqlock-guarded slots." },  // ados_protocol::framebus::RingLayout::VERSION
    ContractMeta { id: "framebus.descriptor", version: 1, wire: "msgpack", transport: "event-bus", status: "active", description: "The small vision.frame descriptor naming a ring slot and its frame geometry." },
    ContractMeta { id: "tap.frame", version: 1, wire: "binary", transport: "unix-stream", status: "active", description: "Vision-tap frame header (ADVT magic) between the video pipeline and the vision engine." },  // ados_protocol::tap::TAP_CONTRACT_VERSION
    ContractMeta { id: "vision.detection", version: 1, wire: "msgpack", transport: "event-bus", status: "active", description: "Structured detection batches published on the vision.detection topic." },
    ContractMeta { id: "atlas.envelope", version: 1, wire: "msgpack", transport: "event-bus", status: "active", description: "Pose-tagged keyframe envelope carried on the atlas topics." },
    ContractMeta { id: "compute", version: 1, wire: "msgpack", transport: "event-bus", status: "active", description: "Compute-offload job submit and read contract." },
    ContractMeta { id: "state.v2", version: 2, wire: "msgpack", transport: "unix-stream", status: "active", description: "Length-prefixed msgpack vehicle-state frame (the current state-socket format)." },
    ContractMeta { id: "frame", version: 0, wire: "binary", transport: "unix-stream", status: "metadata", description: "The 4-byte big-endian length transport primitive shared by plugin.rpc, the MAVLink socket, and state.v2. No version of its own." },
    ContractMeta { id: "mavlink.socket", version: 0, wire: "binary", transport: "unix-stream", status: "metadata", description: "MAVLink frame broadcast socket; framing versioning defers to external MAVLink v1/v2." },
    ContractMeta { id: "rest.openapi", version: 0, wire: "json", transport: "http", status: "metadata", description: "Native control-surface REST API; versioned by the OpenAPI info.version string, not a registry integer." },
    ContractMeta { id: "state.v1", version: 1, wire: "newline-json", transport: "unix-stream", status: "metadata", description: "Legacy newline-terminated JSON vehicle-state frame; superseded by state.v2. No on-wire version integer." },
    ContractMeta { id: "ws_ticket", version: 1, wire: "string", transport: "websocket-subprotocol", status: "metadata", description: "String-tagged (v1) HMAC-SHA256 WebSocket auth ticket; the version is a string tag, not a wire integer." },  // ados_protocol::ws_ticket::TICKET_KEY_LABEL
];

/// Every versioned on-disk state sidecar. The file path is carried in
/// `transport` and the status is `sidecar`.
#[rustfmt::skip]
pub const SIDECARS: &[ContractMeta] = &[
    ContractMeta { id: "atlas-state", version: 1, wire: "json", transport: "/run/ados/plugins/atlas-state.json", status: "sidecar", description: "Atlas capture and world-model state for the GCS plugin panel." },  // ados_atlas::state_sidecar::ATLAS_STATE_SIDECAR
    ContractMeta { id: "atlas-forward", version: 1, wire: "json", transport: "/run/ados/atlas-forward.json", status: "sidecar", description: "Atlas forward-stream state the capture service folds into atlas-state." },  // ados_protocol::atlas::ATLAS_FORWARD_SIDECAR
    ContractMeta { id: "compute-jobs", version: 1, wire: "json", transport: "/run/ados/compute-jobs.json", status: "sidecar", description: "Compute-node job queue snapshot." },  // ados_compute::jobs_sidecar::COMPUTE_JOBS_SIDECAR
    ContractMeta { id: "compute-heartbeat", version: 1, wire: "json", transport: "/run/ados/compute-heartbeat.json", status: "sidecar", description: "Compute-node heartbeat folded into the agent heartbeat." },  // ados_compute::heartbeat_sidecar::COMPUTE_HEARTBEAT_SIDECAR
    ContractMeta { id: "wfb-stats", version: 1, wire: "json", transport: "/run/ados/wfb-stats.json", status: "sidecar", description: "WFB link statistics: RSSI, packet counters, and derived link state." },  // ados_radio::paths::WFB_STATS_JSON
    ContractMeta { id: "hop-supervisor", version: 1, wire: "json", transport: "/run/ados/hop-supervisor.json", status: "sidecar", description: "FHSS hop-supervisor state." },  // ados_radio::paths::HOP_SUPERVISOR_JSON
    ContractMeta { id: "mgmt-link", version: 1, wire: "json", transport: "/run/ados/mgmt-link.json", status: "sidecar", description: "Management-link guardian state." },
    ContractMeta { id: "wifi-powersave", version: 1, wire: "json", transport: "/run/ados/wifi-powersave.json", status: "sidecar", description: "WiFi power-save runtime reconciler state per station interface." },
    ContractMeta { id: "wfb_failover", version: 1, wire: "json", transport: "/run/ados/wfb_failover.json", status: "sidecar", description: "Local-bind to cloud-relay failover state." },
    ContractMeta { id: "bind-state", version: 1, wire: "json", transport: "/run/ados/bind-state.json", status: "sidecar", description: "WFB bind-session sentinel and precheck result." },  // ados_radio::paths::BIND_STATE_SENTINEL
    ContractMeta { id: "mesh-state", version: 1, wire: "json", transport: "/run/ados/mesh-state.json", status: "sidecar", description: "Mesh role and membership state." },  // ados_groundlink::paths::MESH_STATE_JSON
    ContractMeta { id: "camera-state", version: 1, wire: "json", transport: "/run/ados/camera-state.json", status: "sidecar", description: "Camera pipeline readiness state." },  // ados_video::camera_state::CAMERA_STATE_JSON
    ContractMeta { id: "camera-usb-recovery", version: 1, wire: "json", transport: "/run/ados/camera-usb-recovery.json", status: "sidecar", description: "Camera USB-recovery reconciler state." },
    ContractMeta { id: "pic-state", version: 1, wire: "json", transport: "/run/ados/pic-state.json", status: "sidecar", description: "Pilot-in-command arbiter state." },  // ados_hid::paths::PIC_STATE_JSON
    ContractMeta { id: "gpio-output", version: 1, wire: "json", transport: "/run/ados/gpio-output.json", status: "sidecar", description: "Driven GPIO output-line state." },  // ados_gpio::sidecar::GPIO_OUTPUT_PATH
    ContractMeta { id: "board", version: 1, wire: "json", transport: "/run/ados/board.json", status: "sidecar", description: "Detected board fingerprint." },
    ContractMeta { id: "config-status", version: 1, wire: "json", transport: "/run/ados/config-status-<service>.json", status: "sidecar", description: "Per-service config-load status: a loud-fail record written when a service's config is malformed." },
];

/// Look up the registered version of an IPC contract by id.
pub fn contract_version(id: &str) -> Option<u16> {
    CONTRACTS.iter().find(|c| c.id == id).map(|c| c.version)
}

/// Look up the registered version of a state sidecar by id.
pub fn sidecar_version(id: &str) -> Option<u16> {
    SIDECARS.iter().find(|c| c.id == id).map(|c| c.version)
}
