// @generated by scripts/build-design-tokens.py — do not edit.
// Tailwind v3 preset: colours map onto the role variables defined in the
// generated styles/tokens.generated.css that ships beside this preset.

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
        },
        surface: {
          DEFAULT: "hsl(var(--surface) / <alpha-value>)",
          foreground: "hsl(var(--surface-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          hover: "hsl(var(--primary-hover) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        subtle: "hsl(var(--subtle-foreground) / <alpha-value>)",
        signature: "hsl(var(--signature) / <alpha-value>)",
        border: {
          DEFAULT: "hsl(var(--border) / <alpha-value>)",
          strong: "hsl(var(--border-strong) / <alpha-value>)",
        },
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        ok: "hsl(var(--ok) / <alpha-value>)",
        warn: "hsl(var(--warn) / <alpha-value>)",
        serious: "hsl(var(--serious) / <alpha-value>)",
        err: "hsl(var(--err) / <alpha-value>)",
        info: "hsl(var(--info) / <alpha-value>)",
        "on-status": "hsl(var(--on-status) / <alpha-value>)",
        letterbox: "hsl(var(--letterbox) / <alpha-value>)",
        scrim: "var(--scrim)",
        overlay: "var(--overlay-panel)",
        hud: {
          primary: "var(--hud-primary)",
          dim: "var(--hud-dim)",
          ink: "var(--hud-ink)",
          "ink-2": "var(--hud-ink-2)",
          muted: "var(--hud-muted)",
          good: "var(--hud-good)",
          warn: "var(--hud-warn)",
          crit: "var(--hud-crit)",
          lock: "var(--hud-lock)",
          glass: "var(--hud-glass)",
          "glass-strong": "var(--hud-glass-strong)",
          hair: "var(--hud-hair)",
          "hair-2": "var(--hud-hair-2)",
        },
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        display: ["Space Grotesk", "sans-serif"],
      },
      transitionDuration: {
        quick: "200ms",
        base: "320ms",
        scene: "900ms",
      },
      transitionTimingFunction: {
        standard: "ease-out",
        emphasized: "cubic-bezier(0.16,1,0.3,1)",
      },
      backdropBlur: {
        hud: "9px",
      },
    },
  },
};
