# @generated by ados-capabilities-codegen from wfb-adapters.toml. Do not edit by hand.
"""Generated WFB adapter tables (data only).

The source of truth is crates/ados-protocol/wfb-adapters.toml. The
hand-written ``adapter.py`` imports these names so the Python
iw-fallback and mesh relay/receiver adapters share the exact deny-set
the Rust radio service uses, with no second copy to drift.
"""

from __future__ import annotations

WFB_COMPATIBLE: dict[tuple[int, int], str] = {
    (0x0BDA, 0x8812): "RTL8812AU",
    (0x0BDA, 0x881A): "RTL8812AU (alt)",
    (0x0BDA, 0x881B): "RTL8812AU (alt)",
    (0x0BDA, 0x881C): "RTL8812AU (alt)",
    (0x0BDA, 0xA81A): "RTL8812AU (a81a)",
    (0x0BDA, 0xB812): "RTL8812EU",
    (0x2357, 0x0120): "RTL8812AU (TP-Link)",
    (0x2357, 0x0101): "RTL8812AU (TP-Link alt)",
}

WFB_COMPATIBLE_DRIVERS: frozenset[str] = frozenset(
    {
        "8812au",
        "8812eu",
        "rtl8812au",
        "rtl8812eu",
        "rtl88x2eu",
        "rtl88xxau",
    }
)

WFB_DENY_USB_VENDORS: frozenset[int] = frozenset(
    {
        0xA69C,  # AIcSemi AIC8800 family (Rock 5C management WiFi)
    }
)

WFB_DENY_DRIVER_PREFIXES: tuple[str, ...] = (
    "aic8800",  # AIC8800 / AIC8800DC / AIC8800D80 variants
    "brcmfmac",  # Broadcom FullMAC (Pi onboard WiFi)
)
