//! Generates the ADOS capability catalog for all three languages from a single
//! `capabilities.toml` source of truth, so the Python agent catalog, the Rust
//! `ados-protocol` catalog, and the two TypeScript GCS catalogs cannot drift.
//!
//! Usage:
//!   cargo run -p ados-capabilities-codegen            # write all targets
//!   cargo run -p ados-capabilities-codegen -- --check # verify, non-zero on drift
//!
//! Targets whose repository is not checked out (e.g. the GCS sibling in a
//! standalone agent clone) are skipped.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Catalog {
    #[serde(default)]
    agent: Vec<Cap>,
    #[serde(default)]
    gcs: Vec<Cap>,
}

#[derive(Debug, Deserialize)]
struct Cap {
    id: String,
    label: String,
    description: String,
    category: String,
    risk: String,
    risk_reason: String,
    #[serde(default)]
    enforced: bool,
}

const GENERATED_HEADER: &str =
    "ados-capabilities-codegen from capabilities.toml. Do not edit by hand.";

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn emit_rust(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("//! Generated agent capability catalog.\n//!\n");
    out.push_str("//! The source of truth is `capabilities.toml`; regenerate with\n");
    out.push_str("//! `cargo run -p ados-capabilities-codegen`.\n\n");
    out.push_str("/// Human-readable metadata for one capability.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct CapabilityMeta {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub label: &'static str,\n");
    out.push_str("    pub description: &'static str,\n");
    out.push_str("    pub category: &'static str,\n");
    out.push_str("    pub risk: &'static str,\n");
    out.push_str("    pub risk_reason: &'static str,\n");
    out.push_str("    pub enforced: bool,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every agent capability a plugin manifest may declare.\n");
    // The struct-literal rows are long; skip rustfmt on the const so the
    // generated file is fmt-clean without a per-line wrap.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const AGENT_CAPABILITIES: &[CapabilityMeta] = &[\n");
    for c in &cat.agent {
        out.push_str(&format!(
            "    CapabilityMeta {{ id: \"{}\", label: \"{}\", description: \"{}\", category: \"{}\", risk: \"{}\", risk_reason: \"{}\", enforced: {} }},\n",
            esc(&c.id), esc(&c.label), esc(&c.description), esc(&c.category), esc(&c.risk), esc(&c.risk_reason), c.enforced
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// True if `id` is a known agent capability.\n");
    out.push_str("pub fn is_known_agent_capability(id: &str) -> bool {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().any(|c| c.id == id)\n}\n\n");
    out.push_str("/// Look up the metadata for an agent capability.\n");
    out.push_str("pub fn get_agent_capability(id: &str) -> Option<&'static CapabilityMeta> {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().find(|c| c.id == id)\n}\n\n");
    out.push_str("/// Capabilities that have a runtime enforcement gate today.\n");
    out.push_str("pub fn enforced_agent_capabilities() -> impl Iterator<Item = &'static str> {\n");
    out.push_str("    AGENT_CAPABILITIES\n");
    out.push_str("        .iter()\n");
    out.push_str("        .filter(|c| c.enforced)\n");
    out.push_str("        .map(|c| c.id)\n");
    out.push_str("}\n");
    out
}

fn emit_python(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("# @generated by {GENERATED_HEADER}\n"));
    out.push_str("\"\"\"Generated agent capability catalog (data only).\n\n");
    out.push_str(
        "The source of truth is crates/ados-protocol/capabilities.toml. The hand-written\n",
    );
    out.push_str(
        "``capabilities.py`` imports these names and adds the helpers and self-check.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in &cat.agent {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("ENFORCED_AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in cat.agent.iter().filter(|c| c.enforced) {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("CAPABILITY_CATALOG: dict[str, dict[str, str]] = {\n");
    for c in &cat.agent {
        out.push_str(&format!("    \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("        \"label\": \"{}\",\n", esc(&c.label)));
        out.push_str(&format!(
            "        \"description\": \"{}\",\n",
            esc(&c.description)
        ));
        out.push_str(&format!(
            "        \"category\": \"{}\",\n",
            esc(&c.category)
        ));
        out.push_str(&format!("        \"risk\": \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!(
            "        \"risk_reason\": \"{}\",\n",
            esc(&c.risk_reason)
        ));
        out.push_str("    },\n");
    }
    out.push_str("}\n");
    out
}

fn emit_ts_catalog(caps: &[Cap], const_name: &str, with_id_list: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("import type { CapabilityMeta } from \"./capabilities\";\n\n");
    if let Some(list_name) = with_id_list {
        out.push_str(&format!("export const {list_name} = [\n"));
        for c in caps {
            out.push_str(&format!("  \"{}\",\n", esc(&c.id)));
        }
        out.push_str("] as const;\n\n");
    }
    out.push_str(&format!(
        "export const {const_name}: Record<string, CapabilityMeta> = {{\n"
    ));
    for c in caps {
        out.push_str(&format!("  \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("    label: \"{}\",\n", esc(&c.label)));
        out.push_str(&format!("    description: \"{}\",\n", esc(&c.description)));
        out.push_str(&format!("    category: \"{}\",\n", esc(&c.category)));
        out.push_str(&format!("    risk: \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!("    risk_reason: \"{}\",\n", esc(&c.risk_reason)));
        out.push_str("  },\n");
    }
    out.push_str("};\n");
    out
}

struct Target {
    path: PathBuf,
    content: String,
    /// Skip (do not error in --check) when the parent repo is not checked out.
    optional: bool,
}

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");

    // crates/ados-capabilities-codegen -> crates -> ADOSDroneAgent -> Altnautica
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace = manifest.parent().unwrap().to_path_buf();
    let agent_repo = workspace.parent().unwrap().to_path_buf();
    let monorepo = agent_repo.parent().unwrap().to_path_buf();

    let toml_path = workspace.join("ados-protocol/capabilities.toml");
    let raw = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", toml_path.display()));
    let cat: Catalog = toml::from_str(&raw).expect("parse capabilities.toml");

    let gcs_dir = monorepo.join("ADOSMissionControl/src/lib/plugins");

    let targets = vec![
        Target {
            path: workspace.join("ados-protocol/src/capabilities.rs"),
            content: emit_rust(&cat),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/plugins/_capabilities_generated.py"),
            content: emit_python(&cat),
            optional: false,
        },
        Target {
            path: gcs_dir.join("agent-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.agent, "AGENT_CAPABILITY_CATALOG", None),
            optional: true,
        },
        Target {
            path: gcs_dir.join("gcs-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.gcs, "GCS_CAPABILITY_CATALOG", Some("GCS_CAPABILITIES")),
            optional: true,
        },
    ];

    let mut drift = false;
    for t in &targets {
        let parent_exists = t.path.parent().map(Path::exists).unwrap_or(false);
        if t.optional && !parent_exists {
            eprintln!("skip (repo absent): {}", t.path.display());
            continue;
        }
        if check {
            let current = std::fs::read_to_string(&t.path).unwrap_or_default();
            if current != t.content {
                eprintln!(
                    "DRIFT: {} is out of date with capabilities.toml",
                    t.path.display()
                );
                drift = true;
            } else {
                eprintln!("ok: {}", t.path.display());
            }
        } else {
            std::fs::write(&t.path, &t.content)
                .unwrap_or_else(|e| panic!("write {}: {e}", t.path.display()));
            eprintln!("wrote: {}", t.path.display());
        }
    }

    if check && drift {
        eprintln!(
            "\ncapability catalogs are out of sync. Run: cargo run -p ados-capabilities-codegen"
        );
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Catalog {
        Catalog {
            agent: vec![
                Cap {
                    id: "event.publish".into(),
                    label: "Publish".into(),
                    description: "Emit events.".into(),
                    category: "data_network".into(),
                    risk: "low".into(),
                    risk_reason: "Sandboxed.".into(),
                    enforced: true,
                },
                Cap {
                    id: "mavlink.read".into(),
                    label: "Read MAVLink".into(),
                    description: "Observe the stream.".into(),
                    category: "flight_control".into(),
                    risk: "low".into(),
                    risk_reason: "Read-only.".into(),
                    enforced: false,
                },
            ],
            gcs: vec![Cap {
                id: "ui.slot.fc-tab".into(),
                label: "FC tab".into(),
                description: "Add a tab.".into(),
                category: "ui_slot".into(),
                risk: "low".into(),
                risk_reason: "Sandboxed iframe.".into(),
                enforced: false,
            }],
        }
    }

    #[test]
    fn rust_output_has_both_caps_and_enforced_flag() {
        let rs = emit_rust(&sample());
        assert!(rs.contains("id: \"event.publish\""));
        assert!(rs.contains("enforced: true"));
        assert!(rs.contains("id: \"mavlink.read\""));
        assert!(rs.contains("enforced: false"));
        assert!(rs.contains("pub const AGENT_CAPABILITIES"));
    }

    #[test]
    fn python_output_has_frozenset_and_enforced_subset() {
        let py = emit_python(&sample());
        assert!(py.contains("AGENT_CAPABILITIES: frozenset[str]"));
        assert!(py.contains("\"event.publish\","));
        // Only the enforced cap appears in the enforced subset.
        let enforced_block = py
            .split("ENFORCED_AGENT_CAPABILITIES")
            .nth(1)
            .unwrap()
            .split("CAPABILITY_CATALOG")
            .next()
            .unwrap();
        assert!(enforced_block.contains("event.publish"));
        assert!(!enforced_block.contains("mavlink.read"));
    }

    #[test]
    fn ts_gcs_output_has_id_list_and_catalog() {
        let ts = emit_ts_catalog(
            &sample().gcs,
            "GCS_CAPABILITY_CATALOG",
            Some("GCS_CAPABILITIES"),
        );
        assert!(ts.contains("export const GCS_CAPABILITIES = ["));
        assert!(ts.contains("\"ui.slot.fc-tab\","));
        assert!(ts.contains("export const GCS_CAPABILITY_CATALOG: Record<string, CapabilityMeta>"));
    }

    #[test]
    fn escaping_handles_quotes_and_backslashes() {
        assert_eq!(esc(r#"a "b" \c"#), r#"a \"b\" \\c"#);
    }
}
