//! Generates the ADOS capability catalog for all three languages from a single
//! `capabilities.toml` source of truth, so the Python agent catalog, the Rust
//! `ados-protocol` catalog, and the two TypeScript GCS catalogs cannot drift.
//!
//! Usage:
//!   cargo run -p ados-capabilities-codegen            # write all targets
//!   cargo run -p ados-capabilities-codegen -- --check # verify, non-zero on drift
//!
//! Targets whose repository is not checked out (e.g. the GCS sibling in a
//! standalone agent clone) are skipped.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Catalog {
    #[serde(default)]
    agent: Vec<Cap>,
    #[serde(default)]
    gcs: Vec<Cap>,
    #[serde(default)]
    method: Vec<MethodRow>,
}

#[derive(Debug, Deserialize)]
struct Cap {
    id: String,
    label: String,
    description: String,
    category: String,
    risk: String,
    risk_reason: String,
    #[serde(default)]
    enforced: bool,
}

/// One row of the plugin RPC dispatch table: a wire method and the
/// dispatch-level capability the IPC server requires before routing it.
#[derive(Debug, Deserialize)]
struct MethodRow {
    id: String,
    /// The dispatch-level required cap, or `None` when the method is ungated or
    /// gated inline by its handler.
    #[serde(default)]
    required_cap: Option<String>,
    /// Documents that the method has an inline (payload-derived) gate even
    /// though `required_cap` is `None`; emitted as a flag so a reader can tell
    /// an open method (event surface, ping) from an inline-gated one.
    #[serde(default)]
    inline: bool,
}

/// The WFB adapter tables, the single source of truth for the radio adapter
/// classification + management-WiFi deny-set shared by the Rust radio service
/// and the Python iw-fallback / mesh adapters.
#[derive(Debug, Deserialize)]
struct WfbTables {
    #[serde(default)]
    compatible: Vec<WfbCompatible>,
    #[serde(default)]
    driver: Vec<WfbDriver>,
    #[serde(default)]
    deny_vendor: Vec<WfbDenyVendor>,
    #[serde(default)]
    deny_driver: Vec<WfbDenyDriver>,
}

#[derive(Debug, Deserialize)]
struct WfbCompatible {
    vid: u16,
    pid: u16,
    label: String,
}

#[derive(Debug, Deserialize)]
struct WfbDriver {
    name: String,
}

#[derive(Debug, Deserialize)]
struct WfbDenyVendor {
    vid: u16,
    #[serde(default)]
    note: String,
}

#[derive(Debug, Deserialize)]
struct WfbDenyDriver {
    prefix: String,
    #[serde(default)]
    note: String,
}

const GENERATED_HEADER: &str =
    "ados-capabilities-codegen from capabilities.toml. Do not edit by hand.";

/// The `@generated by` provenance line for files emitted from a different
/// source TOML than `capabilities.toml`.
fn generated_header_for(source: &str) -> String {
    format!("ados-capabilities-codegen from {source}. Do not edit by hand.")
}

/// Escape a string for emission inside a double-quoted string literal. The
/// backslash must be escaped first. Control characters are escaped too, so a
/// stray newline/CR/tab in a catalog value cannot corrupt the generated line;
/// the `\n`/`\r`/`\t` escapes are interpreted identically by Rust, Python, and
/// TypeScript double-quoted strings.
fn esc(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn emit_rust(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("//! Generated agent capability catalog.\n//!\n");
    out.push_str("//! The source of truth is `capabilities.toml`; regenerate with\n");
    out.push_str("//! `cargo run -p ados-capabilities-codegen`.\n\n");
    out.push_str("/// Human-readable metadata for one capability.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct CapabilityMeta {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub label: &'static str,\n");
    out.push_str("    pub description: &'static str,\n");
    out.push_str("    pub category: &'static str,\n");
    out.push_str("    pub risk: &'static str,\n");
    out.push_str("    pub risk_reason: &'static str,\n");
    out.push_str("    pub enforced: bool,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every agent capability a plugin manifest may declare.\n");
    // The struct-literal rows are long; skip rustfmt on the const so the
    // generated file is fmt-clean without a per-line wrap.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const AGENT_CAPABILITIES: &[CapabilityMeta] = &[\n");
    for c in &cat.agent {
        out.push_str(&format!(
            "    CapabilityMeta {{ id: \"{}\", label: \"{}\", description: \"{}\", category: \"{}\", risk: \"{}\", risk_reason: \"{}\", enforced: {} }},\n",
            esc(&c.id), esc(&c.label), esc(&c.description), esc(&c.category), esc(&c.risk), esc(&c.risk_reason), c.enforced
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// True if `id` is a known agent capability.\n");
    out.push_str("pub fn is_known_agent_capability(id: &str) -> bool {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().any(|c| c.id == id)\n}\n\n");
    out.push_str("/// Look up the metadata for an agent capability.\n");
    out.push_str("pub fn get_agent_capability(id: &str) -> Option<&'static CapabilityMeta> {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().find(|c| c.id == id)\n}\n\n");
    out.push_str("/// Capabilities that have a runtime enforcement gate today.\n");
    out.push_str("pub fn enforced_agent_capabilities() -> impl Iterator<Item = &'static str> {\n");
    out.push_str("    AGENT_CAPABILITIES\n");
    out.push_str("        .iter()\n");
    out.push_str("        .filter(|c| c.enforced)\n");
    out.push_str("        .map(|c| c.id)\n");
    out.push_str("}\n");
    out
}

fn emit_python(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("# @generated by {GENERATED_HEADER}\n"));
    out.push_str("\"\"\"Generated agent capability catalog (data only).\n\n");
    out.push_str(
        "The source of truth is crates/ados-protocol/capabilities.toml. The hand-written\n",
    );
    out.push_str(
        "``capabilities.py`` imports these names and adds the helpers and self-check.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in &cat.agent {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("ENFORCED_AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in cat.agent.iter().filter(|c| c.enforced) {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("CAPABILITY_CATALOG: dict[str, dict[str, str]] = {\n");
    for c in &cat.agent {
        out.push_str(&format!("    \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("        \"label\": \"{}\",\n", esc(&c.label)));
        out.push_str(&format!(
            "        \"description\": \"{}\",\n",
            esc(&c.description)
        ));
        out.push_str(&format!(
            "        \"category\": \"{}\",\n",
            esc(&c.category)
        ));
        out.push_str(&format!("        \"risk\": \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!(
            "        \"risk_reason\": \"{}\",\n",
            esc(&c.risk_reason)
        ));
        out.push_str("    },\n");
    }
    out.push_str("}\n");
    out
}

/// Format the `required_cap` of one method row as a Rust `Option<&str>` literal.
fn rust_opt(cap: &Option<String>) -> String {
    match cap {
        Some(c) => format!("Some(\"{}\")", esc(c)),
        None => "None".to_string(),
    }
}

/// Format the `required_cap` of one method row as a Python value (a string or
/// `None`).
fn py_opt(cap: &Option<String>) -> String {
    match cap {
        Some(c) => format!("\"{}\"", esc(c)),
        None => "None".to_string(),
    }
}

fn emit_rust_dispatch(methods: &[MethodRow]) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("//! Generated plugin RPC dispatch table.\n//!\n");
    out.push_str("//! Maps every wire method to the dispatch-level capability the plugin IPC\n");
    out.push_str("//! server requires before routing it. The source of truth is the\n");
    out.push_str("//! `[[method]]` section of `capabilities.toml`; regenerate with\n");
    out.push_str("//! `cargo run -p ados-capabilities-codegen`.\n//!\n");
    out.push_str("//! `required_cap` is `None` for the ungated methods (the event surface and\n");
    out.push_str("//! `ping`) and for the methods gated inline by their handler from the\n");
    out.push_str("//! request payload; `inline` distinguishes the two so an open method cannot\n");
    out.push_str("//! be mistaken for an inline-gated one.\n\n");
    out.push_str("/// One row of the dispatch table: a wire method and its dispatch-level gate.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct DispatchMethod {\n");
    out.push_str("    pub method: &'static str,\n");
    out.push_str("    pub required_cap: Option<&'static str>,\n");
    out.push_str("    pub inline: bool,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every plugin RPC method, with the capability the dispatch loop requires\n");
    out.push_str("/// before routing it.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DISPATCH_METHODS: &[DispatchMethod] = &[\n");
    for m in methods {
        out.push_str(&format!(
            "    DispatchMethod {{ method: \"{}\", required_cap: {}, inline: {} }},\n",
            esc(&m.id),
            rust_opt(&m.required_cap),
            m.inline
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// Look up the dispatch-level required capability for a wire method.\n");
    out.push_str("/// Returns `Some(None)` for a known ungated/inline method and `None` for an\n");
    out.push_str("/// unknown method, so a caller can tell the two apart.\n");
    out.push_str("pub fn required_cap_for(method: &str) -> Option<Option<&'static str>> {\n");
    out.push_str("    DISPATCH_METHODS\n");
    out.push_str("        .iter()\n");
    out.push_str("        .find(|m| m.method == method)\n");
    out.push_str("        .map(|m| m.required_cap)\n");
    out.push_str("}\n\n");
    out.push_str("/// True if `method` is a known dispatch method.\n");
    out.push_str("pub fn is_known_method(method: &str) -> bool {\n");
    out.push_str("    DISPATCH_METHODS.iter().any(|m| m.method == method)\n");
    out.push_str("}\n");
    out
}

fn emit_python_dispatch(methods: &[MethodRow]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# @generated by {GENERATED_HEADER}\n"));
    out.push_str("\"\"\"Generated plugin RPC dispatch gate (data only).\n\n");
    out.push_str(
        "The source of truth is the ``[[method]]`` section of\n\
         crates/ados-protocol/capabilities.toml. ``ipc/dispatch.py`` imports\n\
         ``REQUIRED_CAP`` and looks the required cap up from it instead of\n\
         carrying its own copy, so the Rust host and the Python host cannot\n\
         drift — and so a method can never be routed without its gate.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("# Every wire method -> its dispatch-level required cap (or None when the\n");
    out.push_str("# method is ungated or gated inline by its handler).\n");
    out.push_str("REQUIRED_CAP: dict[str, str | None] = {\n");
    for m in methods {
        out.push_str(&format!(
            "    \"{}\": {},\n",
            esc(&m.id),
            py_opt(&m.required_cap)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("# Methods whose cap is decided inline by the handler from the request\n");
    out.push_str("# payload. They have no dispatch-level cap but are NOT open.\n");
    out.push_str("INLINE_GATED: frozenset[str] = frozenset(\n    {\n");
    for m in methods.iter().filter(|m| m.inline) {
        out.push_str(&format!("        \"{}\",\n", esc(&m.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("# Every known wire method.\n");
    out.push_str("KNOWN_METHODS: frozenset[str] = frozenset(REQUIRED_CAP)\n");
    out
}

fn emit_rust_wfb(t: &WfbTables) -> String {
    let header = generated_header_for("wfb-adapters.toml");
    let mut out = String::new();
    out.push_str(&format!("// @generated by {header}\n"));
    out.push_str("//! Generated WFB adapter tables.\n//!\n");
    out.push_str("//! The single source of truth for the radio adapter classification and the\n");
    out.push_str("//! management-WiFi deny-set. The source file is `wfb-adapters.toml`;\n");
    out.push_str("//! regenerate with `cargo run -p ados-capabilities-codegen`.\n\n");

    out.push_str("/// WFB-ng compatible chipsets by (VID, PID) -> label.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const WFB_COMPATIBLE: &[(u16, u16, &str)] = &[\n");
    for c in &t.compatible {
        out.push_str(&format!(
            "    (0x{:04X}, 0x{:04X}, \"{}\"),\n",
            c.vid,
            c.pid,
            esc(&c.label)
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Driver-name fallback for boards whose VID:PID is not yet in the table.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const WFB_COMPATIBLE_DRIVERS: &[&str] = &[\n");
    for d in &t.driver {
        out.push_str(&format!("    \"{}\",\n", esc(&d.name)));
    }
    out.push_str("];\n\n");

    out.push_str("/// Management-WiFi USB vendor deny-set. These radios advertise monitor\n");
    out.push_str("/// mode but cannot inject 802.11 frames, so they must never be tagged\n");
    out.push_str("/// WFB-compatible.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DENY_VID: &[u16] = &[");
    out.push_str(
        &t.deny_vendor
            .iter()
            .map(|v| format!("0x{:04X}", v.vid))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("];\n\n");

    out.push_str("/// Management-WiFi driver-prefix deny-set, denied first so neither the\n");
    out.push_str("/// USB-ID match nor the driver-name fallback can flip them WFB-compatible.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DENY_DRIVER_PREFIXES: &[&str] = &[");
    out.push_str(
        &t.deny_driver
            .iter()
            .map(|d| format!("\"{}\"", esc(&d.prefix)))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("];\n");
    out
}

fn emit_python_wfb(t: &WfbTables) -> String {
    let header = generated_header_for("wfb-adapters.toml");
    let mut out = String::new();
    out.push_str(&format!("# @generated by {header}\n"));
    out.push_str("\"\"\"Generated WFB adapter tables (data only).\n\n");
    out.push_str(
        "The source of truth is crates/ados-protocol/wfb-adapters.toml. The\n\
         hand-written ``adapter.py`` imports these names so the Python\n\
         iw-fallback and mesh relay/receiver adapters share the exact deny-set\n\
         the Rust radio service uses, with no second copy to drift.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("WFB_COMPATIBLE: dict[tuple[int, int], str] = {\n");
    for c in &t.compatible {
        out.push_str(&format!(
            "    (0x{:04X}, 0x{:04X}): \"{}\",\n",
            c.vid,
            c.pid,
            esc(&c.label)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("WFB_COMPATIBLE_DRIVERS: frozenset[str] = frozenset(\n    {\n");
    for d in &t.driver {
        out.push_str(&format!("        \"{}\",\n", esc(&d.name)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("WFB_DENY_USB_VENDORS: frozenset[int] = frozenset(\n    {\n");
    for v in &t.deny_vendor {
        if v.note.is_empty() {
            out.push_str(&format!("        0x{:04X},\n", v.vid));
        } else {
            out.push_str(&format!("        0x{:04X},  # {}\n", v.vid, esc(&v.note)));
        }
    }
    out.push_str("    }\n)\n\n");

    out.push_str("WFB_DENY_DRIVER_PREFIXES: tuple[str, ...] = (\n");
    for d in &t.deny_driver {
        if d.note.is_empty() {
            out.push_str(&format!("    \"{}\",\n", esc(&d.prefix)));
        } else {
            out.push_str(&format!(
                "    \"{}\",  # {}\n",
                esc(&d.prefix),
                esc(&d.note)
            ));
        }
    }
    out.push_str(")\n");
    out
}

fn emit_ts_catalog(caps: &[Cap], const_name: &str, with_id_list: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("import type { CapabilityMeta } from \"./capabilities\";\n\n");
    if let Some(list_name) = with_id_list {
        out.push_str(&format!("export const {list_name} = [\n"));
        for c in caps {
            out.push_str(&format!("  \"{}\",\n", esc(&c.id)));
        }
        out.push_str("] as const;\n\n");
    }
    out.push_str(&format!(
        "export const {const_name}: Record<string, CapabilityMeta> = {{\n"
    ));
    for c in caps {
        out.push_str(&format!("  \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("    label: \"{}\",\n", esc(&c.label)));
        out.push_str(&format!("    description: \"{}\",\n", esc(&c.description)));
        out.push_str(&format!("    category: \"{}\",\n", esc(&c.category)));
        out.push_str(&format!("    risk: \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!("    risk_reason: \"{}\",\n", esc(&c.risk_reason)));
        out.push_str("  },\n");
    }
    out.push_str("};\n");
    out
}

struct Target {
    path: PathBuf,
    content: String,
    /// Skip (do not error in --check) when the parent repo is not checked out.
    optional: bool,
}

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");

    // crates/ados-capabilities-codegen -> crates -> ADOSDroneAgent -> Altnautica
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace = manifest.parent().unwrap().to_path_buf();
    let agent_repo = workspace.parent().unwrap().to_path_buf();
    let monorepo = agent_repo.parent().unwrap().to_path_buf();

    let toml_path = workspace.join("ados-protocol/capabilities.toml");
    let raw = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", toml_path.display()));
    let cat: Catalog = toml::from_str(&raw).expect("parse capabilities.toml");

    let wfb_toml_path = workspace.join("ados-protocol/wfb-adapters.toml");
    let wfb_raw = std::fs::read_to_string(&wfb_toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", wfb_toml_path.display()));
    let wfb: WfbTables = toml::from_str(&wfb_raw).expect("parse wfb-adapters.toml");

    let gcs_dir = monorepo.join("ADOSMissionControl/src/lib/plugins");

    let targets = vec![
        Target {
            path: workspace.join("ados-protocol/src/capabilities.rs"),
            content: emit_rust(&cat),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/plugins/_capabilities_generated.py"),
            content: emit_python(&cat),
            optional: false,
        },
        Target {
            path: workspace.join("ados-protocol/src/dispatch.rs"),
            content: emit_rust_dispatch(&cat.method),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/plugins/_dispatch_generated.py"),
            content: emit_python_dispatch(&cat.method),
            optional: false,
        },
        Target {
            path: workspace.join("ados-protocol/src/wfb_tables.rs"),
            content: emit_rust_wfb(&wfb),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/services/wfb/_wfb_tables_generated.py"),
            content: emit_python_wfb(&wfb),
            optional: false,
        },
        Target {
            path: gcs_dir.join("agent-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.agent, "AGENT_CAPABILITY_CATALOG", None),
            optional: true,
        },
        Target {
            path: gcs_dir.join("gcs-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.gcs, "GCS_CAPABILITY_CATALOG", Some("GCS_CAPABILITIES")),
            optional: true,
        },
    ];

    let mut drift = false;
    for t in &targets {
        let parent_exists = t.path.parent().map(Path::exists).unwrap_or(false);
        if t.optional && !parent_exists {
            eprintln!("skip (repo absent): {}", t.path.display());
            continue;
        }
        if check {
            let current = std::fs::read_to_string(&t.path).unwrap_or_default();
            if current != t.content {
                eprintln!(
                    "DRIFT: {} is out of date with capabilities.toml",
                    t.path.display()
                );
                drift = true;
            } else {
                eprintln!("ok: {}", t.path.display());
            }
        } else {
            std::fs::write(&t.path, &t.content)
                .unwrap_or_else(|e| panic!("write {}: {e}", t.path.display()));
            eprintln!("wrote: {}", t.path.display());
        }
    }

    if check && drift {
        eprintln!(
            "\ncapability catalogs are out of sync. Run: cargo run -p ados-capabilities-codegen"
        );
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Catalog {
        Catalog {
            agent: vec![
                Cap {
                    id: "event.publish".into(),
                    label: "Publish".into(),
                    description: "Emit events.".into(),
                    category: "data_network".into(),
                    risk: "low".into(),
                    risk_reason: "Sandboxed.".into(),
                    enforced: true,
                },
                Cap {
                    id: "mavlink.read".into(),
                    label: "Read MAVLink".into(),
                    description: "Observe the stream.".into(),
                    category: "flight_control".into(),
                    risk: "low".into(),
                    risk_reason: "Read-only.".into(),
                    enforced: false,
                },
            ],
            gcs: vec![Cap {
                id: "ui.slot.fc-tab".into(),
                label: "FC tab".into(),
                description: "Add a tab.".into(),
                category: "ui_slot".into(),
                risk: "low".into(),
                risk_reason: "Sandboxed iframe.".into(),
                enforced: false,
            }],
            method: vec![],
        }
    }

    #[test]
    fn rust_output_has_both_caps_and_enforced_flag() {
        let rs = emit_rust(&sample());
        assert!(rs.contains("id: \"event.publish\""));
        assert!(rs.contains("enforced: true"));
        assert!(rs.contains("id: \"mavlink.read\""));
        assert!(rs.contains("enforced: false"));
        assert!(rs.contains("pub const AGENT_CAPABILITIES"));
    }

    #[test]
    fn python_output_has_frozenset_and_enforced_subset() {
        let py = emit_python(&sample());
        assert!(py.contains("AGENT_CAPABILITIES: frozenset[str]"));
        assert!(py.contains("\"event.publish\","));
        // Only the enforced cap appears in the enforced subset.
        let enforced_block = py
            .split("ENFORCED_AGENT_CAPABILITIES")
            .nth(1)
            .unwrap()
            .split("CAPABILITY_CATALOG")
            .next()
            .unwrap();
        assert!(enforced_block.contains("event.publish"));
        assert!(!enforced_block.contains("mavlink.read"));
    }

    #[test]
    fn ts_gcs_output_has_id_list_and_catalog() {
        let ts = emit_ts_catalog(
            &sample().gcs,
            "GCS_CAPABILITY_CATALOG",
            Some("GCS_CAPABILITIES"),
        );
        assert!(ts.contains("export const GCS_CAPABILITIES = ["));
        assert!(ts.contains("\"ui.slot.fc-tab\","));
        assert!(ts.contains("export const GCS_CAPABILITY_CATALOG: Record<string, CapabilityMeta>"));
    }

    #[test]
    fn escaping_handles_quotes_and_backslashes() {
        assert_eq!(esc(r#"a "b" \c"#), r#"a \"b\" \\c"#);
    }

    fn sample_methods() -> Vec<MethodRow> {
        vec![
            MethodRow {
                id: "ping".into(),
                required_cap: None,
                inline: false,
            },
            MethodRow {
                id: "mission.read".into(),
                required_cap: Some("mission.read".into()),
                inline: false,
            },
            MethodRow {
                id: "mavlink.register_component".into(),
                required_cap: None,
                inline: true,
            },
        ]
    }

    #[test]
    fn rust_dispatch_emits_const_and_lookup() {
        let rs = emit_rust_dispatch(&sample_methods());
        assert!(rs.contains("pub const DISPATCH_METHODS: &[DispatchMethod]"));
        assert!(
            rs.contains("DispatchMethod { method: \"ping\", required_cap: None, inline: false }")
        );
        assert!(rs.contains(
            "DispatchMethod { method: \"mission.read\", required_cap: Some(\"mission.read\"), inline: false }"
        ));
        assert!(rs.contains(
            "DispatchMethod { method: \"mavlink.register_component\", required_cap: None, inline: true }"
        ));
        assert!(rs.contains("pub fn required_cap_for"));
        assert!(rs.contains("pub fn is_known_method"));
    }

    #[test]
    fn python_dispatch_emits_required_cap_map() {
        let py = emit_python_dispatch(&sample_methods());
        assert!(py.contains("REQUIRED_CAP: dict[str, str | None]"));
        assert!(py.contains("\"ping\": None,"));
        assert!(py.contains("\"mission.read\": \"mission.read\","));
        assert!(py.contains("\"mavlink.register_component\": None,"));
        // The inline-gated method is present in the inline set, not None-equals-open.
        let inline_block = py
            .split("INLINE_GATED")
            .nth(1)
            .unwrap()
            .split("KNOWN_METHODS")
            .next()
            .unwrap();
        assert!(inline_block.contains("mavlink.register_component"));
        assert!(!inline_block.contains("\"ping\""));
    }

    fn sample_wfb() -> WfbTables {
        WfbTables {
            compatible: vec![WfbCompatible {
                vid: 0x0BDA,
                pid: 0xB812,
                label: "RTL8812EU".into(),
            }],
            driver: vec![WfbDriver {
                name: "rtl88x2eu".into(),
            }],
            deny_vendor: vec![WfbDenyVendor {
                vid: 0xA69C,
                note: "AIC8800".into(),
            }],
            deny_driver: vec![WfbDenyDriver {
                prefix: "brcmfmac".into(),
                note: "Broadcom".into(),
            }],
        }
    }

    #[test]
    fn rust_wfb_emits_uppercase_hex_consts() {
        let rs = emit_rust_wfb(&sample_wfb());
        assert!(rs.contains("pub const WFB_COMPATIBLE: &[(u16, u16, &str)]"));
        assert!(rs.contains("(0x0BDA, 0xB812, \"RTL8812EU\"),"));
        assert!(rs.contains("pub const WFB_COMPATIBLE_DRIVERS: &[&str]"));
        assert!(rs.contains("\"rtl88x2eu\","));
        assert!(rs.contains("pub const DENY_VID: &[u16] = &[0xA69C];"));
        assert!(rs.contains("pub const DENY_DRIVER_PREFIXES: &[&str] = &[\"brcmfmac\"];"));
    }

    #[test]
    fn python_wfb_emits_dict_and_deny_sets() {
        let py = emit_python_wfb(&sample_wfb());
        assert!(py.contains("WFB_COMPATIBLE: dict[tuple[int, int], str]"));
        assert!(py.contains("(0x0BDA, 0xB812): \"RTL8812EU\","));
        assert!(py.contains("WFB_COMPATIBLE_DRIVERS: frozenset[str]"));
        assert!(py.contains("WFB_DENY_USB_VENDORS: frozenset[int]"));
        assert!(py.contains("0xA69C,  # AIC8800"));
        assert!(py.contains("WFB_DENY_DRIVER_PREFIXES: tuple[str, ...]"));
        assert!(py.contains("\"brcmfmac\",  # Broadcom"));
    }
}
