//! Generates the ADOS capability catalog for all three languages from a single
//! `capabilities.toml` source of truth, so the Python agent catalog, the Rust
//! `ados-protocol` catalog, and the two TypeScript GCS catalogs cannot drift.
//!
//! Usage:
//!   cargo run -p ados-capabilities-codegen            # write all targets
//!   cargo run -p ados-capabilities-codegen -- --check # verify, non-zero on drift
//!
//! Targets whose repository is not checked out (e.g. the GCS sibling in a
//! standalone agent clone) are skipped.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Catalog {
    #[serde(default)]
    agent: Vec<Cap>,
    #[serde(default)]
    gcs: Vec<Cap>,
    #[serde(default)]
    method: Vec<MethodRow>,
}

#[derive(Debug, Deserialize)]
struct Cap {
    id: String,
    label: String,
    description: String,
    category: String,
    risk: String,
    risk_reason: String,
    #[serde(default)]
    enforced: bool,
}

/// One row of the plugin RPC dispatch table: a wire method and the
/// dispatch-level capability the IPC server requires before routing it.
#[derive(Debug, Deserialize)]
struct MethodRow {
    id: String,
    /// The dispatch-level required cap, or `None` when the method is ungated or
    /// gated inline by its handler.
    #[serde(default)]
    required_cap: Option<String>,
    /// Documents that the method has an inline (payload-derived) gate even
    /// though `required_cap` is `None`; emitted as a flag so a reader can tell
    /// an open method (event surface, ping) from an inline-gated one.
    #[serde(default)]
    inline: bool,
}

/// The WFB adapter tables, the single source of truth for the radio adapter
/// classification + management-WiFi deny-set shared by the Rust radio service
/// and the Python iw-fallback / mesh adapters.
#[derive(Debug, Deserialize)]
struct WfbTables {
    #[serde(default)]
    compatible: Vec<WfbCompatible>,
    #[serde(default)]
    driver: Vec<WfbDriver>,
    #[serde(default)]
    deny_vendor: Vec<WfbDenyVendor>,
    #[serde(default)]
    deny_driver: Vec<WfbDenyDriver>,
}

#[derive(Debug, Deserialize)]
struct WfbCompatible {
    vid: u16,
    pid: u16,
    label: String,
}

#[derive(Debug, Deserialize)]
struct WfbDriver {
    name: String,
}

#[derive(Debug, Deserialize)]
struct WfbDenyVendor {
    vid: u16,
    #[serde(default)]
    note: String,
}

#[derive(Debug, Deserialize)]
struct WfbDenyDriver {
    prefix: String,
    #[serde(default)]
    note: String,
}

/// The IPC contract + sidecar version registry: the single source of truth for
/// every inter-process wire-contract version integer and every on-disk
/// state-sidecar version, so the Rust, Python, and TypeScript sides cannot
/// disagree on a contract's version.
#[derive(Debug, Deserialize)]
struct Contracts {
    #[serde(default)]
    contract: Vec<ContractRow>,
    #[serde(default)]
    sidecar: Vec<SidecarRow>,
}

/// One versioned inter-process wire contract.
#[derive(Debug, Deserialize)]
struct ContractRow {
    id: String,
    version: u16,
    #[serde(default)]
    wire: Option<String>,
    #[serde(default)]
    transport: Option<String>,
    #[serde(default)]
    status: Option<String>,
    /// The Rust source-of-truth constant, emitted as a provenance comment on the
    /// generated Rust row so a reader can find the constant a version tracks.
    #[serde(default)]
    rust_const: Option<String>,
    #[serde(default)]
    description: Option<String>,
}

/// One versioned on-disk state sidecar (a JSON file one service writes and
/// another reads). `path` is the sidecar's filesystem location.
#[derive(Debug, Deserialize)]
struct SidecarRow {
    id: String,
    version: u16,
    path: String,
    #[serde(default)]
    rust_const: Option<String>,
    #[serde(default)]
    description: Option<String>,
}

const GENERATED_HEADER: &str =
    "ados-capabilities-codegen from capabilities.toml. Do not edit by hand.";

/// The `@generated by` provenance line for files emitted from a different
/// source TOML than `capabilities.toml`.
fn generated_header_for(source: &str) -> String {
    format!("ados-capabilities-codegen from {source}. Do not edit by hand.")
}

/// Escape a string for emission inside a double-quoted string literal. The
/// backslash must be escaped first. Control characters are escaped too, so a
/// stray newline/CR/tab in a catalog value cannot corrupt the generated line;
/// the `\n`/`\r`/`\t` escapes are interpreted identically by Rust, Python, and
/// TypeScript double-quoted strings.
fn esc(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn emit_rust(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("//! Generated agent capability catalog.\n//!\n");
    out.push_str("//! The source of truth is `capabilities.toml`; regenerate with\n");
    out.push_str("//! `cargo run -p ados-capabilities-codegen`.\n\n");
    out.push_str("/// Human-readable metadata for one capability.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct CapabilityMeta {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub label: &'static str,\n");
    out.push_str("    pub description: &'static str,\n");
    out.push_str("    pub category: &'static str,\n");
    out.push_str("    pub risk: &'static str,\n");
    out.push_str("    pub risk_reason: &'static str,\n");
    out.push_str("    pub enforced: bool,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every agent capability a plugin manifest may declare.\n");
    // The struct-literal rows are long; skip rustfmt on the const so the
    // generated file is fmt-clean without a per-line wrap.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const AGENT_CAPABILITIES: &[CapabilityMeta] = &[\n");
    for c in &cat.agent {
        out.push_str(&format!(
            "    CapabilityMeta {{ id: \"{}\", label: \"{}\", description: \"{}\", category: \"{}\", risk: \"{}\", risk_reason: \"{}\", enforced: {} }},\n",
            esc(&c.id), esc(&c.label), esc(&c.description), esc(&c.category), esc(&c.risk), esc(&c.risk_reason), c.enforced
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// True if `id` is a known agent capability.\n");
    out.push_str("pub fn is_known_agent_capability(id: &str) -> bool {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().any(|c| c.id == id)\n}\n\n");
    out.push_str("/// Look up the metadata for an agent capability.\n");
    out.push_str("pub fn get_agent_capability(id: &str) -> Option<&'static CapabilityMeta> {\n");
    out.push_str("    AGENT_CAPABILITIES.iter().find(|c| c.id == id)\n}\n\n");
    out.push_str("/// Capabilities that have a runtime enforcement gate today.\n");
    out.push_str("pub fn enforced_agent_capabilities() -> impl Iterator<Item = &'static str> {\n");
    out.push_str("    AGENT_CAPABILITIES\n");
    out.push_str("        .iter()\n");
    out.push_str("        .filter(|c| c.enforced)\n");
    out.push_str("        .map(|c| c.id)\n");
    out.push_str("}\n");
    out
}

fn emit_python(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(&format!("# @generated by {GENERATED_HEADER}\n"));
    out.push_str("\"\"\"Generated agent capability catalog (data only).\n\n");
    out.push_str(
        "The source of truth is crates/ados-protocol/capabilities.toml. The hand-written\n",
    );
    out.push_str(
        "``capabilities.py`` imports these names and adds the helpers and self-check.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in &cat.agent {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("ENFORCED_AGENT_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in cat.agent.iter().filter(|c| c.enforced) {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("CAPABILITY_CATALOG: dict[str, dict[str, str]] = {\n");
    for c in &cat.agent {
        out.push_str(&format!("    \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("        \"label\": \"{}\",\n", esc(&c.label)));
        out.push_str(&format!(
            "        \"description\": \"{}\",\n",
            esc(&c.description)
        ));
        out.push_str(&format!(
            "        \"category\": \"{}\",\n",
            esc(&c.category)
        ));
        out.push_str(&format!("        \"risk\": \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!(
            "        \"risk_reason\": \"{}\",\n",
            esc(&c.risk_reason)
        ));
        out.push_str("    },\n");
    }
    out.push_str("}\n\n");

    // The GCS-half capability id set. The browser-side runtime owns the
    // GCS catalog metadata (the two TypeScript catalogs); the agent only
    // needs the id set so the manifest's gcs block can warn on an
    // unrecognised capability without rejecting it.
    out.push_str("GCS_CAPABILITIES: frozenset[str] = frozenset(\n    {\n");
    for c in &cat.gcs {
        out.push_str(&format!("        \"{}\",\n", esc(&c.id)));
    }
    out.push_str("    }\n)\n");
    out
}

/// Format the `required_cap` of one method row as a Rust `Option<&str>` literal.
fn rust_opt(cap: &Option<String>) -> String {
    match cap {
        Some(c) => format!("Some(\"{}\")", esc(c)),
        None => "None".to_string(),
    }
}

/// Format the `required_cap` of one method row as a Python value (a string or
/// `None`).
fn py_opt(cap: &Option<String>) -> String {
    match cap {
        Some(c) => format!("\"{}\"", esc(c)),
        None => "None".to_string(),
    }
}

fn emit_rust_dispatch(methods: &[MethodRow]) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("//! Generated plugin RPC dispatch table.\n//!\n");
    out.push_str("//! Maps every wire method to the dispatch-level capability the plugin IPC\n");
    out.push_str("//! server requires before routing it. The source of truth is the\n");
    out.push_str("//! `[[method]]` section of `capabilities.toml`; regenerate with\n");
    out.push_str("//! `cargo run -p ados-capabilities-codegen`.\n//!\n");
    out.push_str("//! `required_cap` is `None` for the ungated methods (the event surface and\n");
    out.push_str("//! `ping`) and for the methods gated inline by their handler from the\n");
    out.push_str("//! request payload; `inline` distinguishes the two so an open method cannot\n");
    out.push_str("//! be mistaken for an inline-gated one.\n\n");
    out.push_str("/// One row of the dispatch table: a wire method and its dispatch-level gate.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct DispatchMethod {\n");
    out.push_str("    pub method: &'static str,\n");
    out.push_str("    pub required_cap: Option<&'static str>,\n");
    out.push_str("    pub inline: bool,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every plugin RPC method, with the capability the dispatch loop requires\n");
    out.push_str("/// before routing it.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DISPATCH_METHODS: &[DispatchMethod] = &[\n");
    for m in methods {
        out.push_str(&format!(
            "    DispatchMethod {{ method: \"{}\", required_cap: {}, inline: {} }},\n",
            esc(&m.id),
            rust_opt(&m.required_cap),
            m.inline
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// Look up the dispatch-level required capability for a wire method.\n");
    out.push_str("/// Returns `Some(None)` for a known ungated/inline method and `None` for an\n");
    out.push_str("/// unknown method, so a caller can tell the two apart.\n");
    out.push_str("pub fn required_cap_for(method: &str) -> Option<Option<&'static str>> {\n");
    out.push_str("    DISPATCH_METHODS\n");
    out.push_str("        .iter()\n");
    out.push_str("        .find(|m| m.method == method)\n");
    out.push_str("        .map(|m| m.required_cap)\n");
    out.push_str("}\n\n");
    out.push_str("/// True if `method` is a known dispatch method.\n");
    out.push_str("pub fn is_known_method(method: &str) -> bool {\n");
    out.push_str("    DISPATCH_METHODS.iter().any(|m| m.method == method)\n");
    out.push_str("}\n");
    out
}

fn emit_python_dispatch(methods: &[MethodRow]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# @generated by {GENERATED_HEADER}\n"));
    out.push_str("\"\"\"Generated plugin RPC dispatch gate (data only).\n\n");
    out.push_str(
        "The source of truth is the ``[[method]]`` section of\n\
         crates/ados-protocol/capabilities.toml. ``ipc/dispatch.py`` imports\n\
         ``REQUIRED_CAP`` and looks the required cap up from it instead of\n\
         carrying its own copy, so the Rust host and the Python host cannot\n\
         drift — and so a method can never be routed without its gate.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("# Every wire method -> its dispatch-level required cap (or None when the\n");
    out.push_str("# method is ungated or gated inline by its handler).\n");
    out.push_str("REQUIRED_CAP: dict[str, str | None] = {\n");
    for m in methods {
        out.push_str(&format!(
            "    \"{}\": {},\n",
            esc(&m.id),
            py_opt(&m.required_cap)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("# Methods whose cap is decided inline by the handler from the request\n");
    out.push_str("# payload. They have no dispatch-level cap but are NOT open.\n");
    out.push_str("INLINE_GATED: frozenset[str] = frozenset(\n    {\n");
    for m in methods.iter().filter(|m| m.inline) {
        out.push_str(&format!("        \"{}\",\n", esc(&m.id)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("# Every known wire method.\n");
    out.push_str("KNOWN_METHODS: frozenset[str] = frozenset(REQUIRED_CAP)\n");
    out
}

fn emit_rust_wfb(t: &WfbTables) -> String {
    let header = generated_header_for("wfb-adapters.toml");
    let mut out = String::new();
    out.push_str(&format!("// @generated by {header}\n"));
    out.push_str("//! Generated WFB adapter tables.\n//!\n");
    out.push_str("//! The single source of truth for the radio adapter classification and the\n");
    out.push_str("//! management-WiFi deny-set. The source file is `wfb-adapters.toml`;\n");
    out.push_str("//! regenerate with `cargo run -p ados-capabilities-codegen`.\n\n");

    out.push_str("/// WFB-ng compatible chipsets by (VID, PID) -> label.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const WFB_COMPATIBLE: &[(u16, u16, &str)] = &[\n");
    for c in &t.compatible {
        out.push_str(&format!(
            "    (0x{:04X}, 0x{:04X}, \"{}\"),\n",
            c.vid,
            c.pid,
            esc(&c.label)
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Driver-name fallback for boards whose VID:PID is not yet in the table.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const WFB_COMPATIBLE_DRIVERS: &[&str] = &[\n");
    for d in &t.driver {
        out.push_str(&format!("    \"{}\",\n", esc(&d.name)));
    }
    out.push_str("];\n\n");

    out.push_str("/// Management-WiFi USB vendor deny-set. These radios advertise monitor\n");
    out.push_str("/// mode but cannot inject 802.11 frames, so they must never be tagged\n");
    out.push_str("/// WFB-compatible.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DENY_VID: &[u16] = &[");
    out.push_str(
        &t.deny_vendor
            .iter()
            .map(|v| format!("0x{:04X}", v.vid))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("];\n\n");

    out.push_str("/// Management-WiFi driver-prefix deny-set, denied first so neither the\n");
    out.push_str("/// USB-ID match nor the driver-name fallback can flip them WFB-compatible.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const DENY_DRIVER_PREFIXES: &[&str] = &[");
    out.push_str(
        &t.deny_driver
            .iter()
            .map(|d| format!("\"{}\"", esc(&d.prefix)))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("];\n");
    out
}

fn emit_python_wfb(t: &WfbTables) -> String {
    let header = generated_header_for("wfb-adapters.toml");
    let mut out = String::new();
    out.push_str(&format!("# @generated by {header}\n"));
    out.push_str("\"\"\"Generated WFB adapter tables (data only).\n\n");
    out.push_str(
        "The source of truth is crates/ados-protocol/wfb-adapters.toml. The\n\
         hand-written ``adapter.py`` imports these names so the Python\n\
         iw-fallback and mesh relay/receiver adapters share the exact deny-set\n\
         the Rust radio service uses, with no second copy to drift.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("WFB_COMPATIBLE: dict[tuple[int, int], str] = {\n");
    for c in &t.compatible {
        out.push_str(&format!(
            "    (0x{:04X}, 0x{:04X}): \"{}\",\n",
            c.vid,
            c.pid,
            esc(&c.label)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("WFB_COMPATIBLE_DRIVERS: frozenset[str] = frozenset(\n    {\n");
    for d in &t.driver {
        out.push_str(&format!("        \"{}\",\n", esc(&d.name)));
    }
    out.push_str("    }\n)\n\n");

    out.push_str("WFB_DENY_USB_VENDORS: frozenset[int] = frozenset(\n    {\n");
    for v in &t.deny_vendor {
        if v.note.is_empty() {
            out.push_str(&format!("        0x{:04X},\n", v.vid));
        } else {
            out.push_str(&format!("        0x{:04X},  # {}\n", v.vid, esc(&v.note)));
        }
    }
    out.push_str("    }\n)\n\n");

    out.push_str("WFB_DENY_DRIVER_PREFIXES: tuple[str, ...] = (\n");
    for d in &t.deny_driver {
        if d.note.is_empty() {
            out.push_str(&format!("    \"{}\",\n", esc(&d.prefix)));
        } else {
            out.push_str(&format!(
                "    \"{}\",  # {}\n",
                esc(&d.prefix),
                esc(&d.note)
            ));
        }
    }
    out.push_str(")\n");
    out
}

/// One `ContractMeta` struct-literal row for the generated Rust registry. When
/// `rust_const` is present it is appended as a trailing provenance comment so a
/// reader can find the constant a version tracks.
fn contract_row_rust(
    id: &str,
    version: u16,
    wire: &str,
    transport: &str,
    status: &str,
    description: &str,
    rust_const: &Option<String>,
) -> String {
    let mut row = format!(
        "    ContractMeta {{ id: \"{}\", version: {}, wire: \"{}\", transport: \"{}\", status: \"{}\", description: \"{}\" }},",
        esc(id), version, esc(wire), esc(transport), esc(status), esc(description)
    );
    if let Some(rc) = rust_const {
        row.push_str(&format!("  // {rc}"));
    }
    row.push('\n');
    row
}

fn emit_rust_contracts(c: &Contracts) -> String {
    let header = generated_header_for("contracts.toml");
    let mut out = String::new();
    out.push_str(&format!("// @generated by {header}\n"));
    out.push_str("//! Generated IPC contract + sidecar version registry.\n//!\n");
    out.push_str("//! One source of truth for every IPC wire-contract version integer\n");
    out.push_str("//! and every state-sidecar version, for Rust, Python, and TS.\n");
    out.push_str("//! Source: contracts.toml; run ados-capabilities-codegen.\n\n");
    out.push_str("/// Version and wire metadata for one IPC contract or state sidecar.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ContractMeta {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub version: u16,\n");
    out.push_str("    pub wire: &'static str,\n");
    out.push_str("    pub transport: &'static str,\n");
    out.push_str("    pub status: &'static str,\n");
    out.push_str("    pub description: &'static str,\n");
    out.push_str("}\n\n");

    out.push_str("/// Every versioned inter-process wire contract.\n");
    // The struct-literal rows are long; skip rustfmt on the const so the
    // generated file is fmt-clean without a per-line wrap.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const CONTRACTS: &[ContractMeta] = &[\n");
    for row in &c.contract {
        out.push_str(&contract_row_rust(
            &row.id,
            row.version,
            row.wire.as_deref().unwrap_or(""),
            row.transport.as_deref().unwrap_or(""),
            row.status.as_deref().unwrap_or(""),
            row.description.as_deref().unwrap_or(""),
            &row.rust_const,
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Every versioned on-disk state sidecar. The file path is carried in\n");
    out.push_str("/// `transport` and the status is `sidecar`.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const SIDECARS: &[ContractMeta] = &[\n");
    for row in &c.sidecar {
        out.push_str(&contract_row_rust(
            &row.id,
            row.version,
            "json",
            &row.path,
            "sidecar",
            row.description.as_deref().unwrap_or(""),
            &row.rust_const,
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Look up the registered version of an IPC contract by id.\n");
    out.push_str("pub fn contract_version(id: &str) -> Option<u16> {\n");
    out.push_str("    CONTRACTS.iter().find(|c| c.id == id).map(|c| c.version)\n");
    out.push_str("}\n\n");
    out.push_str("/// Look up the registered version of a state sidecar by id.\n");
    out.push_str("pub fn sidecar_version(id: &str) -> Option<u16> {\n");
    out.push_str("    SIDECARS.iter().find(|c| c.id == id).map(|c| c.version)\n");
    out.push_str("}\n");
    out
}

/// One catalog entry for the generated Python registry.
fn py_contract_entry(
    id: &str,
    version: u16,
    wire: &str,
    transport: &str,
    status: &str,
    description: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("    \"{}\": {{\n", esc(id)));
    out.push_str(&format!("        \"version\": {version},\n"));
    out.push_str(&format!("        \"wire\": \"{}\",\n", esc(wire)));
    out.push_str(&format!("        \"transport\": \"{}\",\n", esc(transport)));
    out.push_str(&format!("        \"status\": \"{}\",\n", esc(status)));
    out.push_str(&format!(
        "        \"description\": \"{}\",\n",
        esc(description)
    ));
    out.push_str("    },\n");
    out
}

fn emit_python_contracts(c: &Contracts) -> String {
    let header = generated_header_for("contracts.toml");
    let mut out = String::new();
    out.push_str(&format!("# @generated by {header}\n"));
    out.push_str("\"\"\"Generated IPC contract + sidecar version registry (data only).\n\n");
    out.push_str("The source of truth is crates/ados-protocol/contracts.toml. The hand-written\n");
    out.push_str(
        "``contracts.py`` imports these names and adds the lookup helpers and self-check.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\n");

    out.push_str("CONTRACT_VERSIONS: dict[str, int] = {\n");
    for row in &c.contract {
        out.push_str(&format!("    \"{}\": {},\n", esc(&row.id), row.version));
    }
    out.push_str("}\n\n");

    out.push_str("SIDECAR_VERSIONS: dict[str, int] = {\n");
    for row in &c.sidecar {
        out.push_str(&format!("    \"{}\": {},\n", esc(&row.id), row.version));
    }
    out.push_str("}\n\n");

    out.push_str("CONTRACT_CATALOG: dict[str, dict[str, object]] = {\n");
    for row in &c.contract {
        out.push_str(&py_contract_entry(
            &row.id,
            row.version,
            row.wire.as_deref().unwrap_or(""),
            row.transport.as_deref().unwrap_or(""),
            row.status.as_deref().unwrap_or(""),
            row.description.as_deref().unwrap_or(""),
        ));
    }
    out.push_str("}\n\n");

    out.push_str("SIDECAR_CATALOG: dict[str, dict[str, object]] = {\n");
    for row in &c.sidecar {
        out.push_str(&py_contract_entry(
            &row.id,
            row.version,
            "json",
            &row.path,
            "sidecar",
            row.description.as_deref().unwrap_or(""),
        ));
    }
    out.push_str("}\n");
    out
}

/// One catalog entry for the generated TypeScript registry.
fn ts_contract_entry(
    id: &str,
    version: u16,
    wire: &str,
    transport: &str,
    status: &str,
    description: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("  \"{}\": {{\n", esc(id)));
    out.push_str(&format!("    version: {version},\n"));
    out.push_str(&format!("    wire: \"{}\",\n", esc(wire)));
    out.push_str(&format!("    transport: \"{}\",\n", esc(transport)));
    out.push_str(&format!("    status: \"{}\",\n", esc(status)));
    out.push_str(&format!("    description: \"{}\",\n", esc(description)));
    out.push_str("  },\n");
    out
}

fn emit_ts_contracts(c: &Contracts) -> String {
    let header = generated_header_for("contracts.toml");
    let mut out = String::new();
    out.push_str(&format!("// @generated by {header}\n\n"));

    out.push_str("export const CONTRACT_VERSIONS = {\n");
    for row in &c.contract {
        out.push_str(&format!("  \"{}\": {},\n", esc(&row.id), row.version));
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const SIDECAR_VERSIONS = {\n");
    for row in &c.sidecar {
        out.push_str(&format!("  \"{}\": {},\n", esc(&row.id), row.version));
    }
    out.push_str("} as const;\n\n");

    out.push_str("export interface ContractMeta {\n");
    out.push_str("  version: number;\n");
    out.push_str("  wire: string;\n");
    out.push_str("  transport: string;\n");
    out.push_str("  status: string;\n");
    out.push_str("  description: string;\n");
    out.push_str("}\n\n");

    out.push_str("export const CONTRACT_CATALOG: Record<string, ContractMeta> = {\n");
    for row in &c.contract {
        out.push_str(&ts_contract_entry(
            &row.id,
            row.version,
            row.wire.as_deref().unwrap_or(""),
            row.transport.as_deref().unwrap_or(""),
            row.status.as_deref().unwrap_or(""),
            row.description.as_deref().unwrap_or(""),
        ));
    }
    out.push_str("};\n\n");

    out.push_str("export const SIDECAR_CATALOG: Record<string, ContractMeta> = {\n");
    for row in &c.sidecar {
        out.push_str(&ts_contract_entry(
            &row.id,
            row.version,
            "json",
            &row.path,
            "sidecar",
            row.description.as_deref().unwrap_or(""),
        ));
    }
    out.push_str("};\n");
    out
}

fn emit_ts_catalog(caps: &[Cap], const_name: &str, with_id_list: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(&format!("// @generated by {GENERATED_HEADER}\n"));
    out.push_str("import type { CapabilityMeta } from \"./capabilities\";\n\n");
    if let Some(list_name) = with_id_list {
        out.push_str(&format!("export const {list_name} = [\n"));
        for c in caps {
            out.push_str(&format!("  \"{}\",\n", esc(&c.id)));
        }
        out.push_str("] as const;\n\n");
    }
    out.push_str(&format!(
        "export const {const_name}: Record<string, CapabilityMeta> = {{\n"
    ));
    for c in caps {
        out.push_str(&format!("  \"{}\": {{\n", esc(&c.id)));
        out.push_str(&format!("    label: \"{}\",\n", esc(&c.label)));
        out.push_str(&format!("    description: \"{}\",\n", esc(&c.description)));
        out.push_str(&format!("    category: \"{}\",\n", esc(&c.category)));
        out.push_str(&format!("    risk: \"{}\",\n", esc(&c.risk)));
        out.push_str(&format!("    risk_reason: \"{}\",\n", esc(&c.risk_reason)));
        out.push_str("  },\n");
    }
    out.push_str("};\n");
    out
}

struct Target {
    path: PathBuf,
    content: String,
    /// Skip (do not error in --check) when the parent repo is not checked out.
    optional: bool,
}

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");

    // crates/ados-capabilities-codegen -> crates -> ADOSDroneAgent -> Altnautica
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace = manifest.parent().unwrap().to_path_buf();
    let agent_repo = workspace.parent().unwrap().to_path_buf();
    let monorepo = agent_repo.parent().unwrap().to_path_buf();

    let toml_path = workspace.join("ados-protocol/capabilities.toml");
    let raw = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", toml_path.display()));
    let cat: Catalog = toml::from_str(&raw).expect("parse capabilities.toml");

    let wfb_toml_path = workspace.join("ados-protocol/wfb-adapters.toml");
    let wfb_raw = std::fs::read_to_string(&wfb_toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", wfb_toml_path.display()));
    let wfb: WfbTables = toml::from_str(&wfb_raw).expect("parse wfb-adapters.toml");

    let contracts_toml_path = workspace.join("ados-protocol/contracts.toml");
    let contracts_raw = std::fs::read_to_string(&contracts_toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", contracts_toml_path.display()));
    let contracts: Contracts = toml::from_str(&contracts_raw).expect("parse contracts.toml");

    let gcs_dir = monorepo.join("ADOSMissionControl/src/lib/plugins");

    let targets = vec![
        Target {
            path: workspace.join("ados-protocol/src/capabilities.rs"),
            content: emit_rust(&cat),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/plugins/_capabilities_generated.py"),
            content: emit_python(&cat),
            optional: false,
        },
        Target {
            path: workspace.join("ados-protocol/src/dispatch.rs"),
            content: emit_rust_dispatch(&cat.method),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/plugins/_dispatch_generated.py"),
            content: emit_python_dispatch(&cat.method),
            optional: false,
        },
        Target {
            path: workspace.join("ados-protocol/src/wfb_tables.rs"),
            content: emit_rust_wfb(&wfb),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/services/wfb/_wfb_tables_generated.py"),
            content: emit_python_wfb(&wfb),
            optional: false,
        },
        Target {
            path: workspace.join("ados-protocol/src/contracts.rs"),
            content: emit_rust_contracts(&contracts),
            optional: false,
        },
        Target {
            path: agent_repo.join("src/ados/core/_contracts_generated.py"),
            content: emit_python_contracts(&contracts),
            optional: false,
        },
        Target {
            path: gcs_dir.join("contracts.generated.ts"),
            content: emit_ts_contracts(&contracts),
            optional: true,
        },
        Target {
            path: gcs_dir.join("agent-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.agent, "AGENT_CAPABILITY_CATALOG", None),
            optional: true,
        },
        Target {
            path: gcs_dir.join("gcs-capabilities.generated.ts"),
            content: emit_ts_catalog(&cat.gcs, "GCS_CAPABILITY_CATALOG", Some("GCS_CAPABILITIES")),
            optional: true,
        },
    ];

    let mut drift = false;
    for t in &targets {
        let parent_exists = t.path.parent().map(Path::exists).unwrap_or(false);
        if t.optional && !parent_exists {
            eprintln!("skip (repo absent): {}", t.path.display());
            continue;
        }
        if check {
            let current = std::fs::read_to_string(&t.path).unwrap_or_default();
            if current != t.content {
                eprintln!(
                    "DRIFT: {} is out of date with capabilities.toml",
                    t.path.display()
                );
                drift = true;
            } else {
                eprintln!("ok: {}", t.path.display());
            }
        } else {
            std::fs::write(&t.path, &t.content)
                .unwrap_or_else(|e| panic!("write {}: {e}", t.path.display()));
            eprintln!("wrote: {}", t.path.display());
        }
    }

    if check && drift {
        eprintln!(
            "\ncapability catalogs / contract registry are out of sync. Run: cargo run -p ados-capabilities-codegen"
        );
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Catalog {
        Catalog {
            agent: vec![
                Cap {
                    id: "event.publish".into(),
                    label: "Publish".into(),
                    description: "Emit events.".into(),
                    category: "data_network".into(),
                    risk: "low".into(),
                    risk_reason: "Sandboxed.".into(),
                    enforced: true,
                },
                Cap {
                    id: "mavlink.read".into(),
                    label: "Read MAVLink".into(),
                    description: "Observe the stream.".into(),
                    category: "flight_control".into(),
                    risk: "low".into(),
                    risk_reason: "Read-only.".into(),
                    enforced: false,
                },
            ],
            gcs: vec![Cap {
                id: "ui.slot.fc-tab".into(),
                label: "FC tab".into(),
                description: "Add a tab.".into(),
                category: "ui_slot".into(),
                risk: "low".into(),
                risk_reason: "Sandboxed iframe.".into(),
                enforced: false,
            }],
            method: vec![],
        }
    }

    #[test]
    fn rust_output_has_both_caps_and_enforced_flag() {
        let rs = emit_rust(&sample());
        assert!(rs.contains("id: \"event.publish\""));
        assert!(rs.contains("enforced: true"));
        assert!(rs.contains("id: \"mavlink.read\""));
        assert!(rs.contains("enforced: false"));
        assert!(rs.contains("pub const AGENT_CAPABILITIES"));
    }

    #[test]
    fn python_output_has_frozenset_and_enforced_subset() {
        let py = emit_python(&sample());
        assert!(py.contains("AGENT_CAPABILITIES: frozenset[str]"));
        assert!(py.contains("\"event.publish\","));
        // Only the enforced cap appears in the enforced subset.
        let enforced_block = py
            .split("ENFORCED_AGENT_CAPABILITIES")
            .nth(1)
            .unwrap()
            .split("CAPABILITY_CATALOG")
            .next()
            .unwrap();
        assert!(enforced_block.contains("event.publish"));
        assert!(!enforced_block.contains("mavlink.read"));
    }

    #[test]
    fn ts_gcs_output_has_id_list_and_catalog() {
        let ts = emit_ts_catalog(
            &sample().gcs,
            "GCS_CAPABILITY_CATALOG",
            Some("GCS_CAPABILITIES"),
        );
        assert!(ts.contains("export const GCS_CAPABILITIES = ["));
        assert!(ts.contains("\"ui.slot.fc-tab\","));
        assert!(ts.contains("export const GCS_CAPABILITY_CATALOG: Record<string, CapabilityMeta>"));
    }

    #[test]
    fn escaping_handles_quotes_and_backslashes() {
        assert_eq!(esc(r#"a "b" \c"#), r#"a \"b\" \\c"#);
    }

    fn sample_methods() -> Vec<MethodRow> {
        vec![
            MethodRow {
                id: "ping".into(),
                required_cap: None,
                inline: false,
            },
            MethodRow {
                id: "mission.read".into(),
                required_cap: Some("mission.read".into()),
                inline: false,
            },
            MethodRow {
                id: "mavlink.register_component".into(),
                required_cap: None,
                inline: true,
            },
        ]
    }

    #[test]
    fn rust_dispatch_emits_const_and_lookup() {
        let rs = emit_rust_dispatch(&sample_methods());
        assert!(rs.contains("pub const DISPATCH_METHODS: &[DispatchMethod]"));
        assert!(
            rs.contains("DispatchMethod { method: \"ping\", required_cap: None, inline: false }")
        );
        assert!(rs.contains(
            "DispatchMethod { method: \"mission.read\", required_cap: Some(\"mission.read\"), inline: false }"
        ));
        assert!(rs.contains(
            "DispatchMethod { method: \"mavlink.register_component\", required_cap: None, inline: true }"
        ));
        assert!(rs.contains("pub fn required_cap_for"));
        assert!(rs.contains("pub fn is_known_method"));
    }

    #[test]
    fn python_dispatch_emits_required_cap_map() {
        let py = emit_python_dispatch(&sample_methods());
        assert!(py.contains("REQUIRED_CAP: dict[str, str | None]"));
        assert!(py.contains("\"ping\": None,"));
        assert!(py.contains("\"mission.read\": \"mission.read\","));
        assert!(py.contains("\"mavlink.register_component\": None,"));
        // The inline-gated method is present in the inline set, not None-equals-open.
        let inline_block = py
            .split("INLINE_GATED")
            .nth(1)
            .unwrap()
            .split("KNOWN_METHODS")
            .next()
            .unwrap();
        assert!(inline_block.contains("mavlink.register_component"));
        assert!(!inline_block.contains("\"ping\""));
    }

    fn sample_wfb() -> WfbTables {
        WfbTables {
            compatible: vec![WfbCompatible {
                vid: 0x0BDA,
                pid: 0xB812,
                label: "RTL8812EU".into(),
            }],
            driver: vec![WfbDriver {
                name: "rtl88x2eu".into(),
            }],
            deny_vendor: vec![WfbDenyVendor {
                vid: 0xA69C,
                note: "AIC8800".into(),
            }],
            deny_driver: vec![WfbDenyDriver {
                prefix: "brcmfmac".into(),
                note: "Broadcom".into(),
            }],
        }
    }

    #[test]
    fn rust_wfb_emits_uppercase_hex_consts() {
        let rs = emit_rust_wfb(&sample_wfb());
        assert!(rs.contains("pub const WFB_COMPATIBLE: &[(u16, u16, &str)]"));
        assert!(rs.contains("(0x0BDA, 0xB812, \"RTL8812EU\"),"));
        assert!(rs.contains("pub const WFB_COMPATIBLE_DRIVERS: &[&str]"));
        assert!(rs.contains("\"rtl88x2eu\","));
        assert!(rs.contains("pub const DENY_VID: &[u16] = &[0xA69C];"));
        assert!(rs.contains("pub const DENY_DRIVER_PREFIXES: &[&str] = &[\"brcmfmac\"];"));
    }

    #[test]
    fn python_wfb_emits_dict_and_deny_sets() {
        let py = emit_python_wfb(&sample_wfb());
        assert!(py.contains("WFB_COMPATIBLE: dict[tuple[int, int], str]"));
        assert!(py.contains("(0x0BDA, 0xB812): \"RTL8812EU\","));
        assert!(py.contains("WFB_COMPATIBLE_DRIVERS: frozenset[str]"));
        assert!(py.contains("WFB_DENY_USB_VENDORS: frozenset[int]"));
        assert!(py.contains("0xA69C,  # AIC8800"));
        assert!(py.contains("WFB_DENY_DRIVER_PREFIXES: tuple[str, ...]"));
        assert!(py.contains("\"brcmfmac\",  # Broadcom"));
    }

    fn sample_contracts() -> Contracts {
        Contracts {
            contract: vec![
                ContractRow {
                    id: "plugin.rpc".into(),
                    version: 1,
                    wire: Some("msgpack".into()),
                    transport: Some("unix-stream".into()),
                    status: Some("active".into()),
                    rust_const: Some("ados_protocol::plugin::PROTOCOL_VERSION".into()),
                    description: Some("Plugin RPC envelope.".into()),
                },
                ContractRow {
                    id: "state.v2".into(),
                    version: 2,
                    wire: Some("msgpack".into()),
                    transport: Some("unix-stream".into()),
                    status: Some("active".into()),
                    rust_const: None,
                    description: Some("Length-prefixed msgpack state frame.".into()),
                },
            ],
            sidecar: vec![SidecarRow {
                id: "wfb-stats".into(),
                version: 1,
                path: "/run/ados/wfb-stats.json".into(),
                rust_const: Some("ados_radio::paths::WFB_STATS_JSON".into()),
                description: Some("WFB link statistics.".into()),
            }],
        }
    }

    #[test]
    fn rust_contracts_emits_consts_and_lookups() {
        let rs = emit_rust_contracts(&sample_contracts());
        assert!(rs.contains("pub const CONTRACTS: &[ContractMeta]"));
        assert!(rs.contains("pub const SIDECARS: &[ContractMeta]"));
        assert!(rs.contains("id: \"plugin.rpc\", version: 1"));
        assert!(rs.contains("id: \"state.v2\", version: 2"));
        // The sidecar path is carried in `transport`, status is `sidecar`.
        assert!(rs.contains(
            "id: \"wfb-stats\", version: 1, wire: \"json\", transport: \"/run/ados/wfb-stats.json\", status: \"sidecar\""
        ));
        // rust_const is emitted as a trailing provenance comment, not a struct field.
        assert!(rs.contains(" },  // ados_protocol::plugin::PROTOCOL_VERSION"));
        assert!(rs.contains("pub fn contract_version"));
        assert!(rs.contains("pub fn sidecar_version"));
    }

    #[test]
    fn python_contracts_emits_version_maps_and_catalog() {
        let py = emit_python_contracts(&sample_contracts());
        assert!(py.contains("CONTRACT_VERSIONS: dict[str, int]"));
        assert!(py.contains("\"plugin.rpc\": 1,"));
        assert!(py.contains("\"state.v2\": 2,"));
        assert!(py.contains("SIDECAR_VERSIONS: dict[str, int]"));
        assert!(py.contains("\"wfb-stats\": 1,"));
        assert!(py.contains("CONTRACT_CATALOG: dict[str, dict[str, object]]"));
        assert!(py.contains("SIDECAR_CATALOG: dict[str, dict[str, object]]"));
    }

    #[test]
    fn ts_contracts_emits_const_version_maps_and_catalog() {
        let ts = emit_ts_contracts(&sample_contracts());
        assert!(ts.contains("export const CONTRACT_VERSIONS = {"));
        assert!(ts.contains("\"plugin.rpc\": 1,"));
        assert!(ts.contains("} as const;"));
        assert!(ts.contains("export const SIDECAR_VERSIONS = {"));
        assert!(ts.contains("export interface ContractMeta {"));
        assert!(ts.contains("export const CONTRACT_CATALOG: Record<string, ContractMeta>"));
        assert!(ts.contains("export const SIDECAR_CATALOG: Record<string, ContractMeta>"));
    }

    /// Every ASCII integer on a line, in order (the header counts are the only
    /// integers on their comment lines).
    fn integers_in(line: &str) -> Vec<usize> {
        line.split(|c: char| !c.is_ascii_digit())
            .filter(|s| !s.is_empty())
            .filter_map(|s| s.parse::<usize>().ok())
            .collect()
    }

    /// The first source line containing `needle`.
    fn find_line<'a>(text: &'a str, needle: &str) -> &'a str {
        text.lines()
            .find(|l| l.contains(needle))
            .unwrap_or_else(|| panic!("no line contains {needle:?}"))
    }

    #[test]
    fn header_comment_counts_match_the_catalog() {
        // The `capabilities.toml` section headers carry parenthesised counts
        // (`AGENT capabilities (49)`, `GCS capabilities (20): 10 UI slots + 10 …`,
        // `dispatch table (43)`). They are hand-written documentation that silently
        // rots when a capability is added; pin them to the real entry counts so a
        // drift fails here, not at a confused reader.
        let toml_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("ados-protocol/capabilities.toml");
        let raw = std::fs::read_to_string(&toml_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", toml_path.display()));
        let cat: Catalog = toml::from_str(&raw).expect("parse capabilities.toml");

        let agent_count = cat.agent.len();
        let gcs_count = cat.gcs.len();
        let ui_slot_count = cat.gcs.iter().filter(|c| c.category == "ui_slot").count();
        let method_count = cat.method.len();

        // AGENT header: the single integer is the agent-capability count.
        let agent_header = integers_in(find_line(&raw, "AGENT capabilities ("));
        assert_eq!(
            agent_header.first().copied(),
            Some(agent_count),
            "AGENT capabilities header count != {agent_count} actual"
        );

        // GCS header: (total): N UI slots + M data — total/ui/data must all agree.
        let gcs_header = integers_in(find_line(&raw, "GCS capabilities ("));
        assert_eq!(
            gcs_header,
            vec![gcs_count, ui_slot_count, gcs_count - ui_slot_count],
            "GCS capabilities header (total: ui + data) != actual"
        );

        // Dispatch header: the single integer is the dispatch-method count.
        let dispatch_header = integers_in(find_line(&raw, "dispatch table ("));
        assert_eq!(
            dispatch_header.first().copied(),
            Some(method_count),
            "dispatch table header count != {method_count} actual"
        );
    }
}
