//! @generated by scripts/build-design-tokens.py — do not edit.
//!
//! Amber-on-charcoal terminal palette: 24-bit RGB values and, where the
//! terminal falls back to 256 colours, the nearest xterm index (`*_256`).

#![allow(dead_code)]

/// Charcoal screen background.
pub const CHARCOAL: (u8, u8, u8) = (31, 31, 31);
pub const CHARCOAL_256: u8 = 234;
/// Amber accent (selected / acted-on / the word-mark).
pub const AMBER: (u8, u8, u8) = (235, 193, 87);
pub const AMBER_256: u8 = 179;
/// Lighter amber for the wordmark's vertical gradient.
pub const AMBER_LIGHT: (u8, u8, u8) = (242, 214, 138);
/// Deeper amber for the wordmark's vertical gradient.
pub const AMBER_DEEP: (u8, u8, u8) = (201, 155, 62);
/// Near-white heading / value text.
pub const HEADING: (u8, u8, u8) = (233, 233, 233);
pub const HEADING_256: u8 = 254;
/// Muted grey body / label text.
pub const MUTED: (u8, u8, u8) = (138, 138, 138);
pub const MUTED_256: u8 = 245;
/// Dark text drawn on top of an amber chip / gauge.
pub const ON_AMBER: (u8, u8, u8) = (26, 26, 26);
pub const ON_AMBER_256: u8 = 235;
/// Success green.
pub const SUCCESS: (u8, u8, u8) = (121, 200, 121);
pub const SUCCESS_256: u8 = 114;
/// Warning yellow.
pub const WARNING: (u8, u8, u8) = (227, 199, 102);
pub const WARNING_256: u8 = 179;
/// Destructive salmon red.
pub const DANGER: (u8, u8, u8) = (224, 108, 90);
pub const DANGER_256: u8 = 209;
