# @generated by ados-capabilities-codegen from capabilities.toml. Do not edit by hand.
"""Generated plugin RPC dispatch gate (data only).

The source of truth is the ``[[method]]`` section of
crates/ados-protocol/capabilities.toml. ``ipc/dispatch.py`` imports
``REQUIRED_CAP`` and looks the required cap up from it instead of
carrying its own copy, so the Rust host and the Python host cannot
drift — and so a method can never be routed without its gate.
"""

from __future__ import annotations

# Every wire method -> its dispatch-level required cap (or None when the
# method is ungated or gated inline by its handler).
REQUIRED_CAP: dict[str, str | None] = {
    "event.publish": None,
    "event.subscribe": None,
    "ping": None,
    "telemetry.subscribe": "telemetry.read",
    "telemetry.extend": "telemetry.extend",
    "mission.read": "mission.read",
    "mission.write": "mission.write",
    "recording.start": "recording.write",
    "recording.stop": "recording.write",
    "mavlink.subscribe": "mavlink.read",
    "mavlink.send": "mavlink.write",
    "mavlink.tunnel.send": "mavlink.tunnel",
    "mavlink.register_component": None,
    "peripheral.register_driver": None,
    "peripheral.unregister_driver": None,
    "camera.claim": "sensor.camera.register",
    "camera.release": "sensor.camera.register",
    "camera.get_frame": "sensor.camera.register",
    "config.get": None,
    "config.set": None,
    "process.spawn": "process.spawn",
    "vision.subscribe_frames": "vision.frame.read",
    "vision.register_model": "vision.model.register",
    "vision.infer": "vision.model.register",
    "vision.publish_detection": "vision.detection.publish",
    "vision.subscribe_detections": "vision.detection.subscribe",
    "vision.designate_track": "vision.track.designate",
    "display.page.set": "display.oled.page",
    "gpio.output.set": "hardware.gpio_out",
    "gpio.buzzer.beep": "hardware.gpio_out",
    "flight.guided_setpoint.send": "flight.guided_setpoint",
    "radio.aux_stream.open": "radio.aux_stream",
    "radio.aux_stream.close": "radio.aux_stream",
    "compute.dataset.write": "compute.dataset.write",
    "compute.job.submit": "compute.job.submit",
    "compute.job.read": "compute.job.read",
    "compute.job.outputs": "compute.job.read",
    "compute.job.cancel": "compute.job.submit",
    "compute.stream.open": "compute.stream.open",
    "compute.stream.close": "compute.stream.open",
    "compute.stream.health": "compute.stream.open",
}

# Methods whose cap is decided inline by the handler from the request
# payload. They have no dispatch-level cap but are NOT open.
INLINE_GATED: frozenset[str] = frozenset(
    {
        "mavlink.register_component",
        "peripheral.register_driver",
        "peripheral.unregister_driver",
    }
)

# Every known wire method.
KNOWN_METHODS: frozenset[str] = frozenset(REQUIRED_CAP)
